<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IndikatorStakeholderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('indikator_stakeholder')->delete();

        DB::table('indikator_stakeholder')->insert(array (
            0 => array ('id_indikator' => 1, 'id_stakeholder' => 9),
            1 => array ('id_indikator' => 2, 'id_stakeholder' => 9),
            2 => array ('id_indikator' => 3, 'id_stakeholder' => 5),
            3 => array ('id_indikator' => 4, 'id_stakeholder' => 4),
            4 => array ('id_indikator' => 5, 'id_stakeholder' => 8),
            5 => array ('id_indikator' => 6, 'id_stakeholder' => 9),
            6 => array ('id_indikator' => 7, 'id_stakeholder' => 4),
            7 => array ('id_indikator' => 8, 'id_stakeholder' => 4),
            8 => array ('id_indikator' => 9, 'id_stakeholder' => 4),
            9 => array ('id_indikator' => 10, 'id_stakeholder' => 4),
            10 => array ('id_indikator' => 11, 'id_stakeholder' => 4),
            11 => array ('id_indikator' => 12, 'id_stakeholder' => 4),
            12 => array ('id_indikator' => 13, 'id_stakeholder' => 4),
            13 => array ('id_indikator' => 14, 'id_stakeholder' => 8),
            14 => array ('id_indikator' => 15, 'id_stakeholder' => 4),
            15 => array ('id_indikator' => 16, 'id_stakeholder' => 4),
            16 => array ('id_indikator' => 17, 'id_stakeholder' => 9),
            17 => array ('id_indikator' => 18, 'id_stakeholder' => 9),
            18 => array ('id_indikator' => 19, 'id_stakeholder' => 9),
            19 => array ('id_indikator' => 20, 'id_stakeholder' => 9),
            20 => array ('id_indikator' => 21, 'id_stakeholder' => 4),
            21 => array ('id_indikator' => 22, 'id_stakeholder' => 4),
            22 => array ('id_indikator' => 23, 'id_stakeholder' => 4),
            23 => array ('id_indikator' => 24, 'id_stakeholder' => 4),
            24 => array ('id_indikator' => 25, 'id_stakeholder' => 4),
            25 => array ('id_indikator' => 26, 'id_stakeholder' => 1),
            26 => array ('id_indikator' => 27, 'id_stakeholder' => 6),
            27 => array ('id_indikator' => 28, 'id_stakeholder' => 3),
            28 => array ('id_indikator' => 29, 'id_stakeholder' => 6),
            29 => array ('id_indikator' => 30, 'id_stakeholder' => 4),
            30 => array ('id_indikator' => 31, 'id_stakeholder' => 4),
            31 => array ('id_indikator' => 32, 'id_stakeholder' => 4),
            32 => array ('id_indikator' => 33, 'id_stakeholder' => 4),
            33 => array ('id_indikator' => 34, 'id_stakeholder' => 1),
            34 => array ('id_indikator' => 35, 'id_stakeholder' => 4),
            35 => array ('id_indikator' => 36, 'id_stakeholder' => 4),
            36 => array ('id_indikator' => 37, 'id_stakeholder' => 1),
            37 => array ('id_indikator' => 38, 'id_stakeholder' => 1),
            38 => array ('id_indikator' => 39, 'id_stakeholder' => 1),
            39 => array ('id_indikator' => 40, 'id_stakeholder' => 6),
            40 => array ('id_indikator' => 41, 'id_stakeholder' => 10),
            41 => array ('id_indikator' => 42, 'id_stakeholder' => 10),
            42 => array ('id_indikator' => 43, 'id_stakeholder' => 7),
            43 => array ('id_indikator' => 44, 'id_stakeholder' => 7),
            44 => array ('id_indikator' => 45, 'id_stakeholder' => 10),
            45 => array ('id_indikator' => 46, 'id_stakeholder' => 3),
            46 => array ('id_indikator' => 47, 'id_stakeholder' => 10),
            47 => array ('id_indikator' => 48, 'id_stakeholder' => 10),
            48 => array ('id_indikator' => 49, 'id_stakeholder' => 4),
            49 => array ('id_indikator' => 50, 'id_stakeholder' => 4),
            50 => array ('id_indikator' => 51, 'id_stakeholder' => 4),
            51 => array ('id_indikator' => 52, 'id_stakeholder' => 4),
            52 => array ('id_indikator' => 53, 'id_stakeholder' => 4),
            53 => array ('id_indikator' => 54, 'id_stakeholder' => 4),
            54 => array ('id_indikator' => 55, 'id_stakeholder' => 4),
            55 => array ('id_indikator' => 56, 'id_stakeholder' => 10),
            56 => array ('id_indikator' => 57, 'id_stakeholder' => 10),
            57 => array ('id_indikator' => 58, 'id_stakeholder' => 10),
            58 => array ('id_indikator' => 59, 'id_stakeholder' => 6),
            59 => array ('id_indikator' => 60, 'id_stakeholder' => 10),
            60 => array ('id_indikator' => 61, 'id_stakeholder' => 10),
            61 => array ('id_indikator' => 62, 'id_stakeholder' => 6),
            62 => array ('id_indikator' => 63, 'id_stakeholder' => 4),
            63 => array ('id_indikator' => 64, 'id_stakeholder' => 6),
            64 => array ('id_indikator' => 65, 'id_stakeholder' => 6),
            65 => array ('id_indikator' => 66, 'id_stakeholder' => 10),
            66 => array ('id_indikator' => 67, 'id_stakeholder' => 6),
            67 => array ('id_indikator' => 68, 'id_stakeholder' => 10),
            68 => array ('id_indikator' => 69, 'id_stakeholder' => 4),
            69 => array ('id_indikator' => 70, 'id_stakeholder' => 10),
            70 => array ('id_indikator' => 71, 'id_stakeholder' => 2),
            71 => array ('id_indikator' => 72, 'id_stakeholder' => 5),
            72 => array ('id_indikator' => 73, 'id_stakeholder' => 8),
            73 => array ('id_indikator' => 74, 'id_stakeholder' => 1),
            74 => array ('id_indikator' => 75, 'id_stakeholder' => 1),
            75 => array ('id_indikator' => 76, 'id_stakeholder' => 5),
            76 => array ('id_indikator' => 77, 'id_stakeholder' => 6),
            77 => array ('id_indikator' => 78, 'id_stakeholder' => 5),
            78 => array ('id_indikator' => 79, 'id_stakeholder' => 5),
            79 => array ('id_indikator' => 1, 'id_stakeholder' => 13),
            80 => array ('id_indikator' => 2, 'id_stakeholder' => 13),
            81 => array ('id_indikator' => 3, 'id_stakeholder' => 13),
            82 => array ('id_indikator' => 4, 'id_stakeholder' => 13),
            83 => array ('id_indikator' => 5, 'id_stakeholder' => 13),
            84 => array ('id_indikator' => 6, 'id_stakeholder' => 13),
            85 => array ('id_indikator' => 7, 'id_stakeholder' => 13),
            86 => array ('id_indikator' => 8, 'id_stakeholder' => 13),
            87 => array ('id_indikator' => 9, 'id_stakeholder' => 13),
            88 => array ('id_indikator' => 10, 'id_stakeholder' => 13),
            89 => array ('id_indikator' => 11, 'id_stakeholder' => 13),
            90 => array ('id_indikator' => 12, 'id_stakeholder' => 13),
            91 => array ('id_indikator' => 13, 'id_stakeholder' => 13),
            92 => array ('id_indikator' => 14, 'id_stakeholder' => 13),
            93 => array ('id_indikator' => 15, 'id_stakeholder' => 13),
            94 => array ('id_indikator' => 16, 'id_stakeholder' => 13),
            95 => array ('id_indikator' => 17, 'id_stakeholder' => 13),
            96 => array ('id_indikator' => 18, 'id_stakeholder' => 13),
            97 => array ('id_indikator' => 19, 'id_stakeholder' => 13),
            98 => array ('id_indikator' => 20, 'id_stakeholder' => 13),
            99 => array ('id_indikator' => 21, 'id_stakeholder' => 13),
            100 => array ('id_indikator' => 22, 'id_stakeholder' => 13),
            101 => array ('id_indikator' => 23, 'id_stakeholder' => 13),
            102 => array ('id_indikator' => 24, 'id_stakeholder' => 13),
            103 => array ('id_indikator' => 25, 'id_stakeholder' => 13),
            104 => array ('id_indikator' => 26, 'id_stakeholder' => 13),
            105 => array ('id_indikator' => 27, 'id_stakeholder' => 13),
            106 => array ('id_indikator' => 28, 'id_stakeholder' => 13),
            107 => array ('id_indikator' => 29, 'id_stakeholder' => 13),
            108 => array ('id_indikator' => 30, 'id_stakeholder' => 13),
            109 => array ('id_indikator' => 31, 'id_stakeholder' => 13),
            110 => array ('id_indikator' => 32, 'id_stakeholder' => 13),
            111 => array ('id_indikator' => 33, 'id_stakeholder' => 13),
            112 => array ('id_indikator' => 34, 'id_stakeholder' => 13),
            113 => array ('id_indikator' => 35, 'id_stakeholder' => 13),
            114 => array ('id_indikator' => 36, 'id_stakeholder' => 13),
            115 => array ('id_indikator' => 37, 'id_stakeholder' => 13),
            116 => array ('id_indikator' => 38, 'id_stakeholder' => 13),
            117 => array ('id_indikator' => 39, 'id_stakeholder' => 13),
            118 => array ('id_indikator' => 40, 'id_stakeholder' => 13),
            119 => array ('id_indikator' => 41, 'id_stakeholder' => 13),
            120 => array ('id_indikator' => 42, 'id_stakeholder' => 13),
            121 => array ('id_indikator' => 43, 'id_stakeholder' => 13),
            122 => array ('id_indikator' => 44, 'id_stakeholder' => 13),
            123 => array ('id_indikator' => 45, 'id_stakeholder' => 13),
            124 => array ('id_indikator' => 46, 'id_stakeholder' => 13),
            125 => array ('id_indikator' => 47, 'id_stakeholder' => 13),
            126 => array ('id_indikator' => 48, 'id_stakeholder' => 13),
            127 => array ('id_indikator' => 49, 'id_stakeholder' => 13),
            128 => array ('id_indikator' => 50, 'id_stakeholder' => 13),
            129 => array ('id_indikator' => 51, 'id_stakeholder' => 13),
            130 => array ('id_indikator' => 52, 'id_stakeholder' => 13),
            131 => array ('id_indikator' => 53, 'id_stakeholder' => 13),
            132 => array ('id_indikator' => 54, 'id_stakeholder' => 13),
            133 => array ('id_indikator' => 55, 'id_stakeholder' => 13),
            134 => array ('id_indikator' => 56, 'id_stakeholder' => 13),
            135 => array ('id_indikator' => 57, 'id_stakeholder' => 13),
            136 => array ('id_indikator' => 58, 'id_stakeholder' => 13),
            137 => array ('id_indikator' => 59, 'id_stakeholder' => 13),
            138 => array ('id_indikator' => 60, 'id_stakeholder' => 13),
            139 => array ('id_indikator' => 61, 'id_stakeholder' => 13),
            140 => array ('id_indikator' => 62, 'id_stakeholder' => 13),
            141 => array ('id_indikator' => 63, 'id_stakeholder' => 13),
            142 => array ('id_indikator' => 64, 'id_stakeholder' => 13),
            143 => array ('id_indikator' => 65, 'id_stakeholder' => 13),
            144 => array ('id_indikator' => 66, 'id_stakeholder' => 13),
            145 => array ('id_indikator' => 67, 'id_stakeholder' => 13),
            146 => array ('id_indikator' => 68, 'id_stakeholder' => 13),
            147 => array ('id_indikator' => 69, 'id_stakeholder' => 13),
            148 => array ('id_indikator' => 70, 'id_stakeholder' => 13),
            149 => array ('id_indikator' => 71, 'id_stakeholder' => 13),
            150 => array ('id_indikator' => 72, 'id_stakeholder' => 13),
            151 => array ('id_indikator' => 73, 'id_stakeholder' => 13),
            152 => array ('id_indikator' => 74, 'id_stakeholder' => 13),
            153 => array ('id_indikator' => 75, 'id_stakeholder' => 13),
            154 => array ('id_indikator' => 76, 'id_stakeholder' => 13),
            155 => array ('id_indikator' => 77, 'id_stakeholder' => 13),
            156 => array ('id_indikator' => 78, 'id_stakeholder' => 13),
            157 => array ('id_indikator' => 79, 'id_stakeholder' => 13)
        ));
    }
}
