<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MonevIndikatorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('monev_indikators')->delete();

        DB::table('monev_indikators')->insert(array (
            0 =>
            array (
                'id' => 1,
                'indikator' => 'Luas kawasan hutan',
                'stakeholder1' => 'Kesatuan Pengelolaan Hutan',
                'stakeholder2' => 'Dinas Pekerjaan Umum, Tata Ruang, Perumahan, Kawasan Permukiman, dan Pertanahan; Bappelitbangda',
                'id_intervensi' => 1,
                'id_iku' => 2,
                'id_ikk' => 2,
                'id_terpercaya' => 2,
                'id_landscale' => 2,
                'id_sourceup' => 2,
                'id_kdsd' => 26,
                'target' => '450000',
                'satuan' => 'ha',
                // 'id_capaian' => 1,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            1 =>
            array (
                'id' => 2,
                'indikator' => 'Luas tutupan hutan',
                'stakeholder1' => 'Kesatuan Pengelolaan Hutan',
                'stakeholder2' => '',
                'id_intervensi' => 1,
                'id_iku' => 2,
                'id_ikk' => 2,
                'id_terpercaya' => 2,
                'id_landscale' => 2,
                'id_sourceup' => 3,
                'id_kdsd' => 26,
                'target' => '545000',
                'satuan' => 'ha',
                // 'id_capaian' => 2,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            2 =>
            array (
                'id' => 3,
                'indikator' => 'Luas HCV/HCS',
                'stakeholder1' => 'Kesatuan Pengelolaan Hutan',
                'stakeholder2' => 'Dinas Lingkungan Hidup',
                'id_intervensi' => 1,
                'id_iku' => 2,
                'id_ikk' => 2,
                'id_terpercaya' => 3,
                'id_landscale' => 3,
                'id_sourceup' => 1,
                'id_kdsd' => 26,
                'target' => '234890',
                'satuan' => 'ha',
                // 'id_capaian' => '',
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            3 =>
            array (
                'id' => 4,
                'indikator' => 'Luas alokasi lahan untuk tanaman kakao',
                'stakeholder1' => 'Dinas Pertanian Bidang Perkebunan',
                'stakeholder2' => 'Dinas Pekerjaan Umum, Tata Ruang, Perumahan, Kawasan Permukiman, dan Pertanahan; Bappelitbangda',
                'id_intervensi' => 1,
                'id_iku' => 2,
                'id_ikk' => 3,
                'id_terpercaya' => 1,
                'id_landscale' => 4,
                'id_sourceup' => 1,
                'id_kdsd' => 9,
                'target' => '120000',
                'satuan' => 'ha',
                // 'id_capaian' => 3,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            4 =>
            array (
                'id' => 5,
                'indikator' => 'Luas kakao yang sesuai dengan alokasi lahan',
                'stakeholder1' => 'Dinas Pertanian Bidang Perkebunan',
                'stakeholder2' => 'Dinas Pekerjaan Umum, Tata Ruang, Perumahan, Kawasan Permukiman, dan Pertanahan; Bappelitbangda',
                'id_intervensi' => 1,
                'id_iku' => 2,
                'id_ikk' => 3,
                'id_terpercaya' => 1,
                'id_landscale' => 4,
                'id_sourceup' => 1,
                'id_kdsd' => 9,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 4,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            5 =>
            array (
                'id' => 6,
                'indikator' => 'Luas kakao yang berada pada area perhutanan sosial',
                'stakeholder1' => 'Kesatuan Pengelolaan Hutan',
                'stakeholder2' => 'Dinas Pertanian; Balai Perhutanan Sosial dan Kemitraan Lingkungan',
                'id_intervensi' => 1,
                'id_iku' => 2,
                'id_ikk' => 3,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 6,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            6 =>
            array (
                'id' => 7,
                'indikator' => 'Luas kakao umur produktif',
                'stakeholder1' => 'Dinas Pertanian Bidang Perkebunan',
                'stakeholder2' => 'Bappelitbangda',
                'id_intervensi' => 2,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 7,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            7 =>
            array (
                'id' => 8,
                'indikator' => 'Luas indikatif lahan peremajaan kakao (untuk tanaman tua dan rusak)',
                'stakeholder1' => 'Dinas Pertanian Bidang Perkebunan',
                'stakeholder2' => 'Bappelitbangda',
                'id_intervensi' => 2,
                'id_iku' => 1,
                'id_ikk' => 4,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 9,
                'target' => '60000',
                'satuan' => 'ha',
                // 'id_capaian' => 8,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            8 =>
            array (
                'id' => 9,
                'indikator' => 'Jumlah anggaran peremajaan kakao',
                'stakeholder1' => 'Dinas Pertanian Bidang Perkebunan',
                'stakeholder2' => 'Bappelitbangda',
                'id_intervensi' => 2,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 13,
                'target' => '250000',
                'satuan' => 'juta rupiah',
                // 'id_capaian' => 9,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            9 =>
            array (
                'id' => 10,
                'indikator' => 'Jumlah pendampingan yang diberikan kepada petani untuk peningkatan efektivitas peremajaan kakao',
                'stakeholder1' => 'Dinas Pertanian Bidang Perkebunan',
                'stakeholder2' => '',
                'id_intervensi' => 2,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 6,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 15,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 10,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            10 =>
            array (
                'id' => 11,
                'indikator' => 'Luas penanaman kakao pada area baru dengan kemiringan di atas 25% dengan tingkat kesesuaian lahan S1-S3',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Dinas Lingkungan Hidup; Bappelitbangda; Kesatuan Pengelolaan Hutan',
                'id_intervensi' => 3,
                'id_iku' => 2,
                'id_ikk' => 2,
                'id_terpercaya' => 4,
                'id_landscale' => 2,
                'id_sourceup' => 3,
                'id_kdsd' => 26,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 11,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            11 =>
            array (
                'id' => 12,
                'indikator' => 'Luas lahan kakao yang dikonversi dari lahan tidak produktif (semak belukar, lahan terbuka, padang rumput)',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Dinas Pekerjaan Umum, Tata Ruang, Perumahan, Kawasan Permukiman, dan Pertanahan; Bappelitbangda; Kesatuan Pengelolaan Hutan',
                'id_intervensi' => 3,
                'id_iku' => 2,
                'id_ikk' => 2,
                'id_terpercaya' => 1,
                'id_landscale' => 4,
                'id_sourceup' => 1,
                'id_kdsd' => 9,
                'target' => '12560',
                'satuan' => 'ha',
                // 'id_capaian' => 12,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            12 =>
            array (
                'id' => 13,
                'indikator' => 'Luas agroforestri kakao',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Bappelitbangda, masyarakat, CSO, sektor privat, Dinas Pertanian Provinsi, kementerian terkait',
                'id_intervensi' => 4,
                'id_iku' => 2,
                'id_ikk' => 2,
                'id_terpercaya' => 1,
                'id_landscale' => 5,
                'id_sourceup' => 1,
                'id_kdsd' => 26,
                'target' => '10500',
                'satuan' => 'ha',
                // 'id_capaian' => 13,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            13 =>
            array (
                'id' => 14,
                'indikator' => 'Luas pertambahan tutupan lahan agroforestri kakao',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Bappelitbangda, masyarakat, CSO, sektor privat, Dinas Pertanian Provinsi, kementerian terkait',
                'id_intervensi' => 4,
                'id_iku' => 2,
                'id_ikk' => 2,
                'id_terpercaya' => 1,
                'id_landscale' => 5,
                'id_sourceup' => 1,
                'id_kdsd' => 26,
                'target' => '12000',
                'satuan' => 'ha/tahun',
                // 'id_capaian' => 14,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            14 =>
            array (
                'id' => 15,
                'indikator' => 'Luas lahan tanaman pangan dengan agroforestri kakao',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Bappelitbangda, masyarakat, CSO, sektor privat, Dinas Pertanian Provinsi, kementerian terkait',
                'id_iku' => 1,
                'id_ikk' => 5,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 9,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 15,
                'id_intervensi' => 4,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            15 =>
            array (
                'id' => 16,
                'indikator' => 'Jumlah sertifikasi lahan yang diberikan',
                'stakeholder1' => 'ATR/BPN; Pemerintah Kecamatan dan Desa',
                'stakeholder2' => 'Kelompok tani',
                'id_intervensi' => 5,
                'id_iku' => 3,
                'id_ikk' => 3,
                'id_terpercaya' => 5,
                'id_landscale' => 6,
                'id_sourceup' => 4,
                'id_kdsd' => 7,
                'target' => '1045',
                'satuan' => 'unit',
                // 'id_capaian' => 16,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            16 =>
            array (
                'id' => 17,
                'indikator' => 'Luas lahan kakao yang memperoleh sertifikat',
                'stakeholder1' => 'ATR/BPN; Pemerintah Kecamatan dan Desa',
                'stakeholder2' => 'Kelompok tani',
                'id_intervensi' => 5,
                'id_iku' => 3,
                'id_ikk' => 3,
                'id_terpercaya' => 5,
                'id_landscale' => 6,
                'id_sourceup' => 4,
                'id_kdsd' => 7,
                'target' => '120000',
                'satuan' => 'ha',
                // 'id_capaian' => 17,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            17 =>
            array (
                'id' => 18,
                'indikator' => 'Jumlah penyuluhan dan pendampingan sertifikasi lahan',
                'stakeholder1' => 'ATR/BPN; Pemerintah Kecamatan dan Desa',
                'stakeholder2' => 'Kelompok tani; lembaga keuangan/sektor privat',
                'id_intervensi' => 5,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 5,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 5,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 18,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            18 =>
            array (
                'id' => 19,
                'indikator' => 'Jumlah perhutanan sosial berbasis kakao',
                'stakeholder1' => 'Kesatuan Pengelolaan Hutan',
                'stakeholder2' => 'Dinas Pertanian Bidang Perkebunan; KUPS',
                'id_intervensi' => 6,
                'id_iku' => 1,
                'id_ikk' => 6,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '7',
                'satuan' => 'kelompok',
                // 'id_capaian' => 19,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            19 =>
            array (
                'id' => 20,
                'indikator' => 'Jumlah kemitraan perhutanan sosial yang terjalin ',
                'stakeholder1' => 'Kesatuan Pengelolaan Hutan',
                'stakeholder2' => 'Dinas Pertanian Bidang Perkebunan; KUPS; Sektor privat; Perguruan tinggi',
                'id_intervensi' => 6,
                'id_iku' => 1,
                'id_ikk' => 6,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '7',
                'satuan' => 'paket',
                // 'id_capaian' => 25,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            20 =>
            array (
                'id' => 21,
                'indikator' => 'Jumlah kelembagaan perhutanan sosial yang aktif',
                'stakeholder1' => 'Kesatuan Pengelolaan Hutan',
                'stakeholder2' => 'Dinas Pertanian Bidang Perkebunan; KUPS; Sektor privat; Perguruan tinggi',
                'id_intervensi' => 6,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => '',
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            21 =>
            array (
                'id' => 22,
                'indikator' => 'Jumlah pendampingan kelembagaan perhutanan sosial',
                'stakeholder1' => 'Kesatuan Pengelolaan Hutan',
                'stakeholder2' => 'Dinas Pertanian Bidang Perkebunan; KUPS; Sektor privat; Perguruan tinggi',
                'id_intervensi' => 6,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => '',
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            22 =>
            array (
                'id' => 23,
                'indikator' => 'Jumlah penyuluh berkompetensi',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Kementerian Pertanian; Dinas TPHP Provinsi, cacao doctor/tenaga terlatih; penyuluh swadaya; koperasi; sektor privat',
                'id_intervensi' => 7,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 6,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 15,
                'target' => '250',
                'satuan' => 'orang',
                // 'id_capaian' => 33,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            23 =>
            array (
                'id' => 24,
                'indikator' => 'Rasio penyuluh dan jumlah petani ',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Kementerian Pertanian; Dinas TPHP Provinsi, cacao doctor/tenaga terlatih; penyuluh swadaya; koperasi; sektor privat',
                'id_intervensi' => 7,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 6,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 15,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 34,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            24 =>
            array (
                'id' => 25,
                'indikator' => 'Jumlah kegiatan penyuluhan dalam satu tahun',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Kementerian Pertanian; Dinas TPHP Provinsi, cacao doctor/tenaga terlatih; penyuluh swadaya; koperasi; sektor privat',
                'id_intervensi' => 7,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 6,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 15,
                'target' => '8',
                'satuan' => 'kegiatan',
                // 'id_capaian' => 35,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            25 =>
            array (
                'id' => 26,
                'indikator' => 'Jumlah pelatihan bagi tenaga penyuluh',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Kementerian Pertanian; Dinas TPHP Provinsi, cacao doctor/tenaga terlatih; penyuluh swadaya; koperasi; sektor privat',
                'id_intervensi' => 7,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 15,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 43,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            26 =>
            array (
                'id' => 27,
                'indikator' => 'Jumlah petani yang mengikuti kegiatan penyuluhan ',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Kementerian Pertanian; Dinas TPHP Provinsi, cacao doctor/tenaga terlatih; penyuluh swadaya; koperasi; sektor privat',
                'id_intervensi' => 7,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 6,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 15,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 44,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            27 =>
            array (
                'id' => 28,
            'indikator' => 'Indeks Nilai Tukar Petani (NTP)',
                'stakeholder1' => 'BPS',
                'stakeholder2' => 'Dinas Pertanian; Sektor privat',
                'id_intervensi' => 7,
                'id_iku' => 4,
                'id_ikk' => 9,
                'id_terpercaya' => 7,
                'id_landscale' => 7,
                'id_sourceup' => 5,
                'id_kdsd' => 10,
                'target' => '95',
                'satuan' => '',
                // 'id_capaian' => 47,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            28 =>
            array (
                'id' => 29,
                'indikator' => 'Jumlah koperasi dengan unit usaha berbasis kakao',
                'stakeholder1' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan UKM',
                'stakeholder2' => 'Dinas Pertanian; Dinas Pemberdayaan Masyarakat Desa; Koperasi; Sektor privat; Kelompok tani',
                'id_intervensi' => 8,
                'id_iku' => 1,
                'id_ikk' => 7,
                'id_terpercaya' => 8,
                'id_landscale' => 1,
                'id_sourceup' => 6,
                'id_kdsd' => 4,
                'target' => '100',
                'satuan' => 'unit',
                // 'id_capaian' => 48,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            29 =>
            array (
                'id' => 30,
                'indikator' => 'Jumlah BUMDes dengan unit usaha berbasis kakao',
                'stakeholder1' => 'Dinas Pemberdayaan Masyarakat Desa',
                'stakeholder2' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan UKM; Dinas Pertanian; Kelompok tani; Koperasi; Lembaga keuangan; Sektor privat',
                'id_intervensi' => 8,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 4,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 49,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            30 =>
            array (
                'id' => 31,
                'indikator' => 'Jumlah pemodalan yang diperoleh petani',
                'stakeholder1' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan UKM',
                'stakeholder2' => 'Dinas Pemberdayaan Masyarakt Desa; Dinas Pertanian; Kelompok tani; Koperasi; Lembaga keuangan; Sektor privat',
                'id_intervensi' => 8,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 6,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 3,
                'target' => '',
                'satuan' => 'rupiah',
                // 'id_capaian' => 50,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            31 =>
            array (
                'id' => 32,
                'indikator' => 'Jumlah pendampingan peningkatan kapasitas kelembagaan kakao',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Dinas TPHP Provinsi; Dinas Pemberdayaan Masyarakat Desa; Dinas Perdagangan, Perindustrian, Koperasi, dan UKM; Pemerintah Kecamatan dan Desa; Kelompok tani; Koperasi',
                'id_intervensi' => 8,
                'id_iku' => 1,
                'id_ikk' => 9,
                'id_terpercaya' => 8,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 16,
                'target' => '',
                'satuan' => 'kegiatan',
                // 'id_capaian' => 51,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            32 =>
            array (
                'id' => 33,
                'indikator' => 'Jumlah kemitraan/kerja sama lembaga keuangan petani dengan sektor swasta/LSM/bank ',
                'stakeholder1' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan UKM',
                'stakeholder2' => 'Bank; Kelompok tani; Sektor privat',
                'id_intervensi' => 8,
                'id_iku' => 1,
                'id_ikk' => 9,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 2,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 52,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            33 =>
            array (
                'id' => 34,
                'indikator' => 'Jumlah korporasi petani kakao',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'DPMPTSP; Dinas Perdagangan, Perindustrian, Koperasi, dan UKM; Kelompok tani; Pemerintah Desa; Dinas Pemberdayaan Masyarakat Desa',
                'id_intervensi' => 9,
                'id_iku' => 1,
                'id_ikk' => 9,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 6,
                'id_kdsd' => 18,
                'target' => '5',
                'satuan' => 'unit',
                // 'id_capaian' => 57,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            34 =>
            array (
                'id' => 35,
                'indikator' => 'Jumlah petani yang tergabung dalam korporasi petani',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'DPMPTSP; Dinas Perdagangan, Perindustrian, Koperasi, dan UKM; Kelompok tani; Pemerintah Desa; Dinas Pemberdayaan Masyarakat Desa',
                'id_intervensi' => 9,
                'id_iku' => 1,
                'id_ikk' => 9,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 6,
                'id_kdsd' => 18,
                'target' => '200',
                'satuan' => 'unit',
                // 'id_capaian' => 58,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            35 =>
            array (
                'id' => 36,
                'indikator' => 'Luas lahan yang dikelola',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'DPMPTSP; Dinas Perdagangan, Perindustrian, Koperasi, dan UKM; Kelompok tani; Pemerintah Desa; Dinas Pemberdayaan Masyarakat Desa',
                'id_intervensi' => 9,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 18,
                'target' => '',
                'satuan' => 'ha',
                // 'id_capaian' => 61,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            36 =>
            array (
                'id' => 37,
                'indikator' => 'Pendapatan petani kakao',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Dinas Pemberdayaan Masyarakat Desa; Dinas Perdagangan, Perindustrian, Koperasi, dan UKM; Koperasi',
                'id_intervensi' => 9,
                'id_iku' => 4,
                'id_ikk' => 8,
                'id_terpercaya' => 1,
                'id_landscale' => 7,
                'id_sourceup' => 7,
                'id_kdsd' => 20,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => '',
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            37 =>
            array (
                'id' => 38,
                'indikator' => 'Jumlah pendampingan peningkatan kapasitas korporasi petani',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Dinas Pemberdayaan Masyarakat Desa; Dinas Perdagangan, Perindustrian, Koperasi, dan UKM; Kelompok tani; Koperasi',
                'id_intervensi' => 9,
                'id_iku' => 1,
                'id_ikk' => 9,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 15,
                'target' => '',
                'satuan' => 'kegiatan',
                // 'id_capaian' => 63,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            38 =>
            array (
                'id' => 39,
                'indikator' => 'Jumlah peralatan pertanian yang terdistribusi dan sesuai dengan kebutuhan petani',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Dinas Pertanian Provinsi; Sektor privat; Lembaga keuangan; DP2KM; CSO',
                'id_intervensi' => 10,
                'id_iku' => 1,
                'id_ikk' => 9,
                'id_terpercaya' => 6,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 19,
                'target' => '20',
                'satuan' => 'unit',
                // 'id_capaian' => 64,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            39 =>
            array (
                'id' => 40,
                'indikator' => 'Jumlah kelompok tani yang mendapatkan bantuan peralatan pertanian',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Dinas Pertanian Provinsi; Sektor privat; Lembaga keuangan; DP2KM; CSO',
                'id_intervensi' => 10,
                'id_iku' => 1,
                'id_ikk' => 9,
                'id_terpercaya' => 6,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 19,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 68,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            40 =>
            array (
                'id' => 41,
                'indikator' => 'Indeks Nilai Tukar Petani (NTP)',
                'stakeholder1' => 'BPS',
                'stakeholder2' => 'Dinas Pertanian; Sektor privat',
                'id_intervensi' => 10,
                'id_iku' => 4,
                'id_ikk' => 8,
                'id_terpercaya' => 7,
                'id_landscale' => 7,
                'id_sourceup' => 5,
                'id_kdsd' => 11,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 69,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            41 =>
            array (
                'id' => 42,
                'indikator' => 'Jumlah kelompok perempuan tani kakao produktif',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Dinas Pemberdayaan Perempuan, Perlindungan Anak, Pengendalian Penduduk, dan Keluarga Berencana; Dinas Pemberdayaan Masyarakat Desa; Dinas Perikanan dan Ketahanan Pangan; Sektor Privat; Dinas Sosial',
                'id_intervensi' => 11,
                'id_iku' => 1,
                'id_ikk' => 9,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 6,
                'id_kdsd' => 1,
                'target' => '20',
                'satuan' => 'kelompok',
                // 'id_capaian' => 70,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            42 =>
            array (
                'id' => 43,
                'indikator' => 'Jumlah petani perempuan yang mengikuti penyuluhan pertanian, termasuk usaha tani',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Dinas Pemberdayaan Perempuan, Perlindungan Anak, Pengendalian Penduduk, dan Keluarga Berencana; Dinas Pemberdayaan Masyarakat Desa; Dinas Perikanan dan Ketahanan Pangan; Sektor Privat; Dinas Sosial',
                'id_intervensi' => 11,
                'id_iku' => 1,
                'id_ikk' => 10,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 71,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            43 =>
            array (
                'id' => 44,
                'indikator' => 'Jumlah petani perempuan yang mengikuti penyuluhan non pertanian',
                'stakeholder1' => 'Dinas Sosial',
                'stakeholder2' => 'Dinas Pemberdayaan Masyarakat Desa; Dinas Perdagangan, Perindustrian, Koperasi, dan UKM; Sektor Privat; Dinas Kesehatan; Dinas Pemberdayaan Perempuan dan Perlindungan Anak',
                'id_iku' => 1,
                'id_ikk' => 10,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '256',
                'satuan' => 'orang',
                // 'id_capaian' => 72,
                'id_intervensi' => 11,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            44 =>
            array (
                'id' => 45,
                'indikator' => 'Jumlah unit usaha pengolahan kakao yang dikelola oleh kelompok perempuan',
                'stakeholder1' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan UKM',
                'stakeholder2' => 'Dinas Pemberdayaan Perempuan, Perlindungan Anak, Pengendalian Penduduk, dan Keluarga Berencana; Dinas Pemberdayaan Masyarakat Desa; Koperasi; Sektor Privat',
                'id_intervensi' => 11,
                'id_iku' => 1,
                'id_ikk' => 10,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '100',
                'satuan' => 'unit',
                // 'id_capaian' => 73,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            45 =>
            array (
                'id' => 46,
                'indikator' => 'Jumlah kelompok tani perempuan yang mendapatkan bantuan peralatan pertanian',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Dinas Pertanian Provinsi; Dinas Perikanan dan Ketahanan Pangan; Dinas Pemberdayaan Perempuan, Perlindungan Anak, Pengendalian Penduduk, dan Keluarga Berencana; Dinas Pemberdayaan Masyarakat Desa; Kelompok tani; Dinas Sosial',
                'id_intervensi' => 11,
                'id_iku' => 1,
                'id_ikk' => 10,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'kelompok',
                // 'id_capaian' => 74,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            46 =>
            array (
                'id' => 47,
                'indikator' => 'Bantuan permodalan bagi unit usaha yang dikelola kelompok perempuan',
                'stakeholder1' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan UKM',
                'stakeholder2' => 'Dinas Pertanian Provinsi; Dinas Pertanian Kabupaten; Dinas Perikanan dan Ketahanan Pangan; Dinas Pemberdayaan Perempuan, Perlindungan Anak, Pengendalian Penduduk, dan Keluarga Berencana; Dinas Pemberdayaan Masyarakat Desa; Kelompok tani; Dinas Sosial',
                'id_intervensi' => 11,
                'id_iku' => 1,
                'id_ikk' => 10,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'rupiah',
                // 'id_capaian' => 75,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            47 =>
            array (
                'id' => 48,
                'indikator' => 'Jumlah pelatihan K3 kepada petani',
                'stakeholder1' => 'Dinas Kesehatan',
                'stakeholder2' => 'Sektor privat; Dinas Transmigrasi dan Tenaga Kerja',
                'id_iku' => 1,
                'id_ikk' => 11,
                'id_terpercaya' => 1,
                'id_landscale' => 8,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '3',
                'satuan' => 'kegiatan',
                // 'id_capaian' => 76,
                'id_intervensi' => 12,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            48 =>
            array (
                'id' => 49,
                'indikator' => 'Jumlah petani yang memiliki alat keselamatan kerja',
                'stakeholder1' => 'Dinas Kesehatan',
                'stakeholder2' => 'Sektor privat; Dinas Transmigrasi dan Tenaga Kerja',
                'id_intervensi' => 12,
                'id_iku' => 1,
                'id_ikk' => 11,
                'id_terpercaya' => 1,
                'id_landscale' => 8,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'orang',
                // 'id_capaian' => 81,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            49 =>
            array (
                'id' => 50,
                'indikator' => 'Jumlah keluarga petani yang mendapat edukasi perlindungan anak',
                'stakeholder1' => 'Dinas Pemberdayaan Perempuan, Perlindungan Anak, Pengendalian Penduduk, dan Keluarga Berencana',
                'stakeholder2' => 'Dinas Sosial; Kelompok tani; Sektor privat',
                'id_intervensi' => 13,
                'id_iku' => 1,
                'id_ikk' => 11,
                'id_terpercaya' => 1,
                'id_landscale' => 9,
                'id_sourceup' => 8,
                'id_kdsd' => 1,
                'target' => '257',
                'satuan' => 'Rumah Tangga',
                // 'id_capaian' => 82,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            50 =>
            array (
                'id' => 51,
                'indikator' => 'SOP pencegahan dan pengawasan di tingkat komunitas',
                'stakeholder1' => 'Dinas Pemberdayaan Perempuan, Perlindungan Anak, Pengendalian Penduduk, dan Keluarga Berencana',
                'stakeholder2' => 'Dinas Transmigrasi dan Tenaga Kerja; Sektor privat; Pemerintah Desa; Dinas Pemberdayaan Masyarakat Desa',
                'id_intervensi' => 13,
                'id_iku' => 1,
                'id_ikk' => 11,
                'id_terpercaya' => 1,
                'id_landscale' => 9,
                'id_sourceup' => 8,
                'id_kdsd' => 1,
                'target' => '1',
                'satuan' => 'dokumen',
                // 'id_capaian' => 83,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            51 =>
            array (
                'id' => 52,
                'indikator' => 'Keberadaan regulasi/produk hukum yang mendukung pengembangan kakao lestari ',
                'stakeholder1' => 'Bappelitbangda',
                'stakeholder2' => 'Dinas Pertanian; Biro Hukum; Badan Legislatif DPRD',
                'id_intervensi' => 14,
                'id_iku' => 5,
                'id_ikk' => 1,
                'id_terpercaya' => 9,
                'id_landscale' => 4,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '1',
                'satuan' => 'dokumen',
                // 'id_capaian' => 84,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            52 =>
            array (
                'id' => 53,
                'indikator' => 'Keberadaan sistem monitoring dan evaluasi kakao lestari',
                'stakeholder1' => 'Dinas Komunikasi dan Informatika',
                'stakeholder2' => 'Dinas Pertanian; Bappelitbangda',
                'id_intervensi' => 14,
                'id_iku' => 1,
                'id_ikk' => 12,
                'id_terpercaya' => 1,
                'id_landscale' => 4,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 85,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            53 =>
            array (
                'id' => 54,
                'indikator' => 'Jumlah kegiatan konsultasi dan sosialisasi kebijakan kepada kelompok tani dan kelompok tani perempuan',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Bappelitbangda; Dinas Pemberdayaan Masyarakat Desa; Pemerintah Kecamatan dan Desa; DP3AP2KB',
                'id_intervensi' => 14,
                'id_iku' => 1,
                'id_ikk' => 13,
                'id_terpercaya' => 9,
                'id_landscale' => 10,
                'id_sourceup' => 1,
                'id_kdsd' => 8,
                'target' => 'kegiatan',
                'satuan' => '',
                // 'id_capaian' => 86,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            54 =>
            array (
                'id' => 55,
                'indikator' => 'Integrasi kebijakan kakao lestari dalam Master Plan dan RPJMD/Des (terutama desa yanag memiliki komoditas strategis kakao)',
                'stakeholder1' => 'Bappelitbangda',
                'stakeholder2' => 'Pemerintah Desa; Dinas Pemberdayaan Masyarakat Desa; Dinas PUPR',
                'id_intervensi' => 14,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 9,
                'id_landscale' => 10,
                'id_sourceup' => 1,
                'id_kdsd' => 22,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 87,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            55 =>
            array (
                'id' => 56,
                'indikator' => 'Volume pembiayaan dana desa bagi pengelolaan kakao lestari',
                'stakeholder1' => 'Dinas Pemberdayaan Masyarakat Desa',
                'stakeholder2' => 'Pemerintah Desa; Dinas Pertanian',
                'id_intervensi' => 14,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => '%/tahun',
                // 'id_capaian' => 88,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            56 =>
            array (
                'id' => 57,
                'indikator' => 'Jumlah petani kakao yang menerima program asuransi pertanian',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Bank BUMN/BUMN; Dinas Pemberdayaan Masyarakat Desa; Kelompok tani; BPJS; Sektor privat',
                'id_intervensi' => 15,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 13,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 13,
                'target' => '100',
                'satuan' => 'orang',
                // 'id_capaian' => 89,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            57 =>
            array (
                'id' => 58,
                'indikator' => 'Perjanjian kerja sama dengan lembaga asuransi',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Bank BUMN/BUMN; Dinas Pemberdayaan Masyarakat Desa; Kelompok tani; BPJS; Sektor privat',
                'id_intervensi' => 15,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 13,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 13,
                'target' => '25',
                'satuan' => 'unit',
                // 'id_capaian' => 92,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            58 =>
            array (
                'id' => 59,
                'indikator' => 'Asuransi pertanian terintegrasi dengan program pemerintah untuk kakao lestari ',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Bank BUMN/BUMN; Dinas Pemberdayaan Masyarakat Desa; Kelompok tani; BPJS; Sektor privat',
                'id_intervensi' => 15,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => '',
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            59 =>
            array (
                'id' => 60,
                'indikator' => 'Jumlah kebun induk kakao dan penangkar bibit kakao bersertifikat',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Kelompok tani; Penangkar/produsen benih; Sektor privat; UPTD Perbenihan Provinsi',
                'id_intervensi' => 16,
                'id_iku' => 1,
                'id_ikk' => 4,
                'id_terpercaya' => 5,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '45',
                'satuan' => 'unit',
                // 'id_capaian' => 95,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            60 =>
            array (
                'id' => 61,
                'indikator' => 'Keberagaman jenis dan luas area varietas kakao dalam kebun',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Kelompok tani; Sektor privat; ICCRI; Dinas TPHP Provinsi',
                'id_intervensi' => 16,
                'id_iku' => 1,
                'id_ikk' => 4,
                'id_terpercaya' => 1,
                'id_landscale' => 12,
                'id_sourceup' => 4,
                'id_kdsd' => 1,
                'target' => '10',
                'satuan' => 'jenis',
                // 'id_capaian' => 96,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),

            61 =>
            array (
                'id' => 62,
                'indikator' => 'Jumlah petani dan luas yang menggunakan bahan tanam resisten OPT',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Kelompok tani; Sektor privat; ICCRI; Dinas TPHP Provinsi',
                'id_iku' => 1,
                'id_ikk' => 4,
                'id_terpercaya' => 1,
                'id_landscale' => 12,
                'id_sourceup' => 4,
                'id_kdsd' => 1,
                'target' => '256',
                'satuan' => 'orang',
                // 'id_capaian' => 97,
                'id_intervensi' => 16,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            62 =>
            array (
                'id' => 63,
                'indikator' => 'Jumlah petani yang menggunakan benih/bibit kakao unggul (bersertifikat)',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Kelompok tani; Penangkar/produsen benih; Sektor privat; Dinas TPHP Provinsi; UPT BSMBP ',
                'id_intervensi' => 16,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 13,
                'id_landscale' => 12,
                'id_sourceup' => 4,
                'id_kdsd' => 13,
                'target' => 'orang',
                'satuan' => '256',
                // 'id_capaian' => 98,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            63 =>
            array (
                'id' => 64,
                'indikator' => 'Produksi kakao',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Kelompok tani; Sektor privat',
                'id_intervensi' => 16,
                'id_iku' => 6,
                'id_ikk' => 4,
                'id_terpercaya' => 1,
                'id_landscale' => 13,
                'id_sourceup' => 4,
                'id_kdsd' => 10,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 101,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            64 =>
            array (
                'id' => 65,
                'indikator' => 'Produktivitas kakao',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Kelompok tani; Sektor privat',
                'id_intervensi' => 16,
                'id_iku' => 6,
                'id_ikk' => 4,
                'id_terpercaya' => 7,
                'id_landscale' => 13,
                'id_sourceup' => 4,
                'id_kdsd' => 10,
                'target' => '12000',
                'satuan' => 'ton/ha/tahun',
                // 'id_capaian' => 102,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            65 =>
            array (
                'id' => 66,
                'indikator' => 'Jumlah produsen pupuk organik',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => '',
                'id_intervensi' => 16,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 13,
                'id_landscale' => 11,
                'id_sourceup' => 4,
                'id_kdsd' => 13,
                'target' => '',
                'satuan' => 'unit',
                // 'id_capaian' => 103,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            66 =>
            array (
                'id' => 67,
                'indikator' => 'Jumlah petani yang menggunakan pupuk organik dan penggunaan kapur pertanian',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => '',
                'id_intervensi' => 16,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 13,
                'id_landscale' => 11,
                'id_sourceup' => 4,
                'id_kdsd' => 13,
                'target' => '',
                'satuan' => 'orang',
                // 'id_capaian' => 104,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            67 =>
            array (
                'id' => 68,
                'indikator' => 'Jumlah petani yang menerapkan teknik konservasi tanah ',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => '',
                'id_intervensi' => 16,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 17,
                'id_sourceup' => 4,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'orang',
                // 'id_capaian' => 105,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            68 =>
            array (
                'id' => 69,
                'indikator' => 'Jumlah petani yang mengelola agroforestri kakao',
                'stakeholder1' => 'Dinas Tanaman Pangan, Hortikultura dan Perkebunan',
                'stakeholder2' => '',
                'id_intervensi' => 16,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 12,
                'id_sourceup' => 4,
                'id_kdsd' => 13,
                'target' => '',
                'satuan' => 'orang',
                // 'id_capaian' => 106,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            69 =>
            array (
                'id' => 70,
                'indikator' => 'Jumlah petani yang mendapatkan pelatihan agroforestri kakao',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => '',
                'id_intervensi' => 16,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 13,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 13,
                'target' => '',
                'satuan' => 'orang',
                // 'id_capaian' => 107,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            70 =>
            array (
                'id' => 71,
                'indikator' => 'Jumlah kios dan akses yang mudah terhadap pupuk bersubsidi khusus kakao',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Kelompok tani; Sektor privat',
                'id_intervensi' => 17,
                'id_iku' => 1,
                'id_ikk' => 4,
                'id_terpercaya' => 13,
                'id_landscale' => 11,
                'id_sourceup' => 4,
                'id_kdsd' => 13,
                'target' => '',
                'satuan' => 'unit',
                // 'id_capaian' => 111,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            71 =>
            array (
                'id' => 72,
                'indikator' => 'Adanya sistem informasi tanaman kakao (termasuk pupuk) bagi petani',
                'stakeholder1' => 'Dinas Komunikasi dan Informatika',
                'stakeholder2' => 'Dinas Pertanian; Sektor privat',
                'id_intervensi' => 17,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 112,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            72 =>
            array (
                'id' => 73,
                'indikator' => 'Jumlah petani dengan pembibitan mandiri',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Kelompok tani; Sektor privat',
                'id_intervensi' => 17,
                'id_iku' => 1,
                'id_ikk' => 4,
                'id_terpercaya' => 13,
                'id_landscale' => 11,
                'id_sourceup' => 4,
                'id_kdsd' => 13,
                'target' => '',
                'satuan' => 'orang',
                // 'id_capaian' => 113,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            73 =>
            array (
                'id' => 74,
                'indikator' => 'Jumlah pelatihan dan peningkatan kapasitas petani dalam peningkatan mutu dan pasca panen',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Kelompok tani; Sektor privat; Dinas Perdagangan, Perindustrian, Koperasi, dan UKM; Dinas TPHP Provinsi; Kementerian Pertanian',
                'id_intervensi' => 18,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 13,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 13,
                'target' => '',
                'satuan' => 'kegiatan',
                // 'id_capaian' => 114,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            74 =>
            array (
                'id' => 75,
                'indikator' => 'Jumlah petani yang dilatih untuk peningkatan mutu dan pasca panen',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Kelompok tani; Sektor privat; Dinas Perdagangan, Perindustrian, Koperasi, dan UKM; Dinas TPHP Provinsi; Kementerian Pertanian',
                'id_intervensi' => 18,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 13,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 22,
                'target' => '',
                'satuan' => 'orang',
                // 'id_capaian' => 115,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            75 =>
            array (
                'id' => 76,
                'indikator' => 'Nilai tambah bruto bisnis industri hilir skala kecil',
                'stakeholder1' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan UKM',
                'stakeholder2' => 'Dinas Pertanian; Dinas Pemberdayaan Masyarakat Desa',
                'id_intervensi' => 18,
                'id_iku' => 6,
                'id_ikk' => 16,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 23,
                'target' => '100000',
                'satuan' => 'rupiah',
                // 'id_capaian' => 119,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            76 =>
            array (
                'id' => 77,
                'indikator' => 'Volume produksi kakao fermentasi',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Koperasi; Kelompok tani; Dinas Perdagangan, Perindustrian, Koperasi, dan UKM',
                'id_intervensi' => 18,
                'id_iku' => 6,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '6000',
                'satuan' => 'ton',
                // 'id_capaian' => 120,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            77 =>
            array (
                'id' => 78,
                'indikator' => 'Jumlah unit usaha produk kakao yang dikelola petani laki-laki dan perempuan',
                'stakeholder1' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan UKM',
                'stakeholder2' => 'Koperasi; Kelompok tani; Sektor privat',
                'id_intervensi' => 18,
                'id_iku' => 6,
                'id_ikk' => 16,
                'id_terpercaya' => 10,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 22,
                'target' => '',
                'satuan' => 'unit',
                // 'id_capaian' => 121,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            78 =>
            array (
                'id' => 79,
                'indikator' => 'Jumlah jenis produk kakao yang dihasilkan kelompok petani/masyarakat',
                'stakeholder1' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan UKM',
                'stakeholder2' => 'Koperasi; Kelompok tani; Sektor privat; Dinas Pertanian',
                'id_intervensi' => 18,
                'id_iku' => 1,
                'id_ikk' => 16,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'unit',
                // 'id_capaian' => 122,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            79 =>
            array (
                'id' => 80,
                'indikator' => 'Jumlah pelaku UKM berbasis kakao',
                'stakeholder1' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan UKM',
                'stakeholder2' => 'Dinas Pertanian; Koperasi; Kelompok tani; Sektor privat',
                'id_intervensi' => 19,
                'id_iku' => 6,
                'id_ikk' => 16,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 24,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 124,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            80 =>
            array (
                'id' => 81,
                'indikator' => 'Kemitraan dengan sektor swasta/pembeli',
                'stakeholder1' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan UKM',
                'stakeholder2' => 'Sektor privat; Dinas Pertanian; DPMPTSP',
                'id_intervensi' => 19,
                'id_iku' => 1,
                'id_ikk' => 16,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '156',
                'satuan' => 'unit',
                // 'id_capaian' => 125,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            81 =>
            array (
                'id' => 82,
                'indikator' => 'Kuantitas biji dengan kelas mutu I dan II (SNI 2323:2008)',
                'stakeholder1' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan UKM',
                'stakeholder2' => 'Sektor privat; Koperasi; Kelompok tani',
                'id_intervensi' => 20,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'ton',
                // 'id_capaian' => 126,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            82 =>
            array (
                'id' => 83,
                'indikator' => 'Margin harga yang diterima petani',
                'stakeholder1' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan UKM',
                'stakeholder2' => 'Dinas Pertanian; Kelompok tani',
                'id_intervensi' => 20,
                'id_iku' => 4,
                'id_ikk' => 15,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'rupiah',
                // 'id_capaian' => 129,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            83 =>
            array (
                'id' => 84,
                'indikator' => 'Jumlah koperasi petani kakao termasuk BUMDes, unit usaha/bisnis berbasis kakao dan kelompok usaha tani kakao',
                'stakeholder1' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan UKM',
                'stakeholder2' => 'Dinas Pertanian; Koperasi; Sektor privat; Dinas Pemberdayaan Masyarakat Desa',
                'id_intervensi' => 20,
                'id_iku' => 6,
                'id_ikk' => 16,
                'id_terpercaya' => 8,
                'id_landscale' => 1,
                'id_sourceup' => 6,
                'id_kdsd' => 21,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 130,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            84 =>
            array (
                'id' => 85,
                'indikator' => 'Kemitraan BUMDes/koperasi dengan kelompok tani kakao',
                'stakeholder1' => 'Dinas Pemberdayaan Masyarakat Desa',
                'stakeholder2' => 'Dinas Pertanian; Dinas Perdagangan, Perindustrian, Koperasi, dan UKM; Koperasi',
                'id_intervensi' => 20,
                'id_iku' => 1,
                'id_ikk' => 7,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 21,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 131,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            85 =>
            array (
                'id' => 86,
                'indikator' => 'Jumlah petani yang melakukan pengarsipan dokumen dan pencatatan usaha tani',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Koperasi; Dinas Perdagangan, Perindustrian, Koperasi, dan UKM; Sektor privat',
                'id_intervensi' => 21,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'orang',
                // 'id_capaian' => 132,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            86 =>
            array (
                'id' => 87,
                'indikator' => 'Keberadaan perangkat lunak pelacakan yang open access',
                'stakeholder1' => 'Dinas Komunikasi dan Informatika',
                'stakeholder2' => 'Dinas Pertanian; Dinas Perdagangan, Perindustrian, Koperasi, dan UKM; Sektor privat; Perguruan tinggi; Koperasi',
                'id_intervensi' => 22,
                'id_iku' => 8,
                'id_ikk' => 12,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 133,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            87 =>
            array (
                'id' => 88,
                'indikator' => 'Sistem informasi geografis komoditas kakao Luwu Utara',
                'stakeholder1' => 'Dinas Komunikasi dan Informatika',
                'stakeholder2' => 'Dinas Pertanian',
                'id_intervensi' => 22,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 25,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 134,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            88 =>
            array (
                'id' => 89,
                'indikator' => 'Jumlah petani yang memiliki informasi koordinat',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Kelompok tani; Sektor privat',
                'id_intervensi' => 22,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 5,
                'id_landscale' => 1,
                'id_sourceup' => 4,
                'id_kdsd' => 14,
                'target' => '',
                'satuan' => 'orang',
                // 'id_capaian' => 135,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            89 =>
            array (
                'id' => 90,
                'indikator' => 'Jumlah petani yang memiliki sertifikasi komoditas kakao berkelanjutan',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Kelompok tani; Sektor privat',
                'id_intervensi' => 22,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 5,
                'id_landscale' => 1,
                'id_sourceup' => 4,
                'id_kdsd' => 14,
                'target' => '',
                'satuan' => 'orang',
                // 'id_capaian' => 137,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            90 =>
            array (
                'id' => 91,
                'indikator' => 'Insentif sertifikasi kakao bagi petani',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Kelompok tani; Sektor privat',
                'id_intervensi' => 22,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 5,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 14,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 140,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            91 =>
            array (
                'id' => 92,
                'indikator' => 'Laju erosi',
                'stakeholder1' => 'Dinas Lingkungan Hidup',
                'stakeholder2' => 'Kesatuan Pengelolaan Hutan; Pemerintah Desa',
                'id_intervensi' => 23,
                'id_iku' => 2,
                'id_ikk' => 2,
                'id_terpercaya' => 3,
                'id_landscale' => 2,
                'id_sourceup' => 3,
                'id_kdsd' => 26,
                'target' => '1',
                'satuan' => 'ton/ha/tahun',
                // 'id_capaian' => 141,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            92 =>
            array (
                'id' => 93,
                'indikator' => 'Debit air sungai',
                'stakeholder1' => 'Dinas Lingkungan Hidup',
                'stakeholder2' => '',
                'id_intervensi' => 23,
                'id_iku' => 2,
                'id_ikk' => 2,
                'id_terpercaya' => 3,
                'id_landscale' => 3,
                'id_sourceup' => 1,
                'id_kdsd' => 26,
                'target' => '100',
                'satuan' => 'm3/s',
                // 'id_capaian' => 142,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            93 =>
            array (
                'id' => 94,
                'indikator' => 'Emisi GRK lahan pertanian dan kehutanan ',
                'stakeholder1' => 'Dinas Lingkungan Hidup',
                'stakeholder2' => 'Kesatuan Pengelolaan Hutan; DLHK Provinsi; Kemeterian terkait; Sektor privat',
                'id_intervensi' => 23,
                'id_iku' => 2,
                'id_ikk' => 2,
                'id_terpercaya' => 11,
                'id_landscale' => 19,
                'id_sourceup' => 3,
                'id_kdsd' => 26,
                'target' => '',
                'satuan' => 'ton CO2eq/tahun',
                // 'id_capaian' => 143,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            94 =>
            array (
                'id' => 95,
                'indikator' => 'Luas tutupan lahan agroforestri/berbasis pohon yang mengikuti kontrak JLH berbasis performa di tingkat sub-DAS',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Dinas Lingkungan Hidup; Kementerian terkait; Sektor privat',
                'id_intervensi' => 23,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 144,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            95 =>
            array (
                'id' => 96,
                'indikator' => 'Volume pembiayaan pemerintah untuk mendukung biaya TAKE dan biaya transfer KIJLH',
                'stakeholder1' => 'Dinas Pemberdayaan Masyarakat Desa',
                'stakeholder2' => 'Dinas Lingkungan Hidup; Bappelitbangda',
                'id_intervensi' => 23,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'rupiah',
                // 'id_capaian' => 145,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            96 =>
            array (
                'id' => 97,
                'indikator' => 'Jumlah program RENSTRA terkait pengelolaan jasa lingkungan',
                'stakeholder1' => 'Bappelitbangda',
                'stakeholder2' => 'Dinas Pemberdayaan Masyarakat Desa; Dinas Lingkungan Hidup; Pemerintah Desa',
                'id_intervensi' => 23,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'program',
                // 'id_capaian' => '',
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            97 =>
            array (
                'id' => 98,
                'indikator' => 'Jumlah petani peserta PJLH',
                'stakeholder1' => 'Dinas Pemberdayaan Masyarakat Desa',
                'stakeholder2' => 'Dinas Lingkungan Hidup; Kementerian terkait; Sektor privat',
                'id_intervensi' => 24,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 6,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'orang',
                // 'id_capaian' => 149,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            98 =>
            array (
                'id' => 99,
                'indikator' => 'Luas tutupan lahan agroforestri/berbasis pohon yang mengikuti PJLH berbasis performa',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => 'Dinas Lingkungan Hidup; Kementerian terkait; Sektor privat',
                'id_intervensi' => 24,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 150,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            99 =>
            array (
                'id' => 100,
                'indikator' => 'Jumlah perusahaan mitra PJLH',
                'stakeholder1' => 'Dinas Pemberdayaan Masyarakat Desa',
                'stakeholder2' => 'Pemerintah Desa; Sektor privat',
                'id_intervensi' => 24,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'unit',
                // 'id_capaian' => 151,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            100 =>
            array (
                'id' => 101,
                'indikator' => 'Jumlah skema PJLH yang operasional dan berkesinambungan ',
                'stakeholder1' => 'Dinas Pemberdayaan Masyarakat Desa',
                'stakeholder2' => 'Pemerintah Desa; Sektor privat',
                'id_intervensi' => 24,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'unit',
                // 'id_capaian' => 152,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            101 =>
            array (
                'id' => 102,
                'indikator' => 'Jumlah produk kakao Luwu Utara yang memperoleh label ramah lingkungan hidup',
                'stakeholder1' => 'Dinas Pertanian',
                'stakeholder2' => '',
                'id_intervensi' => 25,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 5,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 17,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 153,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            102 =>
            array (
                'id' => 103,
                'indikator' => 'Volume dana penanggulangan, pencemaran dan/atau kerusakan dan pemulihan lingkungan hidup',
                'stakeholder1' => 'Dinas Lingkungan Hidup',
                'stakeholder2' => 'Dinas Pemberdayaan Masyarakat Desa; Pemerintah Desa; Sektor privat',
                'id_intervensi' => 26,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 5,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 154,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            103 =>
            array (
                'id' => 104,
                'indikator' => 'Jumlah perusahaan, kelompok masyarakat, maupun perorangan yang mendapat penghargaan kinerja di bidang perlindungan lingkungan',
                'stakeholder1' => 'Dinas Lingkungan Hidup',
                'stakeholder2' => 'Kelompok tani; Koperasi; Sektor privat',
                'id_intervensi' => 27,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 156,
                'dokumen' => '',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            )
        ));
    }
}
