<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MonevIndikatorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('monev_indikators')->delete();

        DB::table('monev_indikators')->insert(array (
            0 =>
            array (
                'id' => 1,
                'indikator' => 'Luas kawasan hutan',
                'stakeholder1' => 'KPH',
                'stakeholder2' => 'KPH',
                'id_intervensi' => 1,
                'id_iku' => 2,
                'id_ikk' => 2,
                'id_terpercaya' => 2,
                'id_landscale' => 2,
                'id_sourceup' => 2,
                'id_kdsd' => 26,
                'target' => '542715,715002153',
                'satuan' => 'ha',
                // 'id_capaian' => 1,
                'dokumen' => 'Peta penunjukkan/penetapan kawasan',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            1 =>
            array (
                'id' => 2,
                'indikator' => 'Luas tutupan hutan',
                'stakeholder1' => 'KPH',
                'stakeholder2' => 'KPH',
                'id_intervensi' => 1,
                'id_iku' => 2,
                'id_ikk' => 2,
                'id_terpercaya' => 2,
                'id_landscale' => 2,
                'id_sourceup' => 3,
                'id_kdsd' => 26,
                'target' => '526722,406039303',
                'satuan' => 'ha',
                // 'id_capaian' => 2,
                'dokumen' => 'Peta tutupan/penggunaan lahan',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            2 =>
            array (
                'id' => 3,
                'indikator' => 'Luas HCV/HCS',
                'stakeholder1' => 'DLH',
                'stakeholder2' => 'DLH',
                'id_intervensi' => 1,
                'id_iku' => 2,
                'id_ikk' => 2,
                'id_terpercaya' => 3,
                'id_landscale' => 3,
                'id_sourceup' => 1,
                'id_kdsd' => 26,
                'target' => '',
                'satuan' => 'ha',
                // 'id_capaian' => '',
                'dokumen' => 'Peta HCV/HCS',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            3 =>
            array (
                'id' => 4,
                'indikator' => 'Luas alokasi lahan untuk tanaman kakao',
                'stakeholder1' => 'Distan',
                'stakeholder2' => 'Distan',
                'id_intervensi' => 1,
                'id_iku' => 2,
                'id_ikk' => 3,
                'id_terpercaya' => 1,
                'id_landscale' => 4,
                'id_sourceup' => 1,
                'id_kdsd' => 9,
                'target' => '',
                'satuan' => 'ha',
                // 'id_capaian' => 3,
                'dokumen' => 'Peta tutupan/penggunaan lahan dengan kelas lahan kakao',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            4 =>
            array (
                'id' => 5,
                'indikator' => 'Persentase luas kakao yang sesuai dengan alokasi lahan',
                'stakeholder1' => 'DPUTRPKP2',
                'stakeholder2' => 'DPUTRPKP2',
                'id_intervensi' => 1,
                'id_iku' => 2,
                'id_ikk' => 3,
                'id_terpercaya' => 1,
                'id_landscale' => 4,
                'id_sourceup' => 1,
                'id_kdsd' => 9,
                'target' => '100',
                'satuan' => '%',
                // 'id_capaian' => 4,
                'dokumen' => 'Peta tutupan/penggunaan lahan dengan kelas lahan kakao',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            5 =>
            array (
                'id' => 6,
                'indikator' => 'Persentase luas kakao yang berada pada area perhutanan sosial',
                'stakeholder1' => 'KPH',
                'stakeholder2' => 'KPH',
                'id_intervensi' => 1,
                'id_iku' => 2,
                'id_ikk' => 3,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => '%',
                // 'id_capaian' => 6,
                'dokumen' => 'Peta tutupan/penggunaan lahan di area perhutanan sosial',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            6 =>
            array (
                'id' => 7,
                'indikator' => 'Persentase luas kakao umur produktif',
                'stakeholder1' => 'Distan',
                'stakeholder2' => 'Distan',
                'id_intervensi' => 2,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '80',
                'satuan' => '%',
                // 'id_capaian' => 7,
                'dokumen' => 'Data tabular umur dan luas kebun kakao masyarakat',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            7 =>
            array (
                'id' => 8,
                'indikator' => 'Luas indikatif lahan peremajaan kakao (untuk tanaman tua dan rusak)',
                'stakeholder1' => 'Distan',
                'stakeholder2' => 'Distan',
                'id_intervensi' => 2,
                'id_iku' => 1,
                'id_ikk' => 4,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 9,
                'target' => '10989',
                'satuan' => 'ha',
                // 'id_capaian' => 8,
                'dokumen' => 'Data tabular luas dan lokasi target dan realisasi lahan peremajaan kakao',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            8 =>
            array (
                'id' => 9,
                'indikator' => 'Jumlah pendampingan yang diberikan kepada petani untuk peningkatan efektivitas peremajaan kakao',
                'stakeholder1' => 'Distan',
                'stakeholder2' => 'Distan',
                'id_intervensi' => 2,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 6,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 15,
                'target' => '40',
                'satuan' => 'kegiatan ',
                // 'id_capaian' => 10,
                'dokumen' => 'Data kegiatan penyuluhan untuk petani kakao dari berbagai lembaga',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            9 =>
            array (
                'id' => 10,
                'indikator' => 'Persentase penanaman kakao pada area baru dengan kemiringan di atas 25% dengan tingkat kesesuaian lahan S1-S3',
                'stakeholder1' => 'Distan',
                'stakeholder2' => 'Distan',
                'id_intervensi' => 3,
                'id_iku' => 2,
                'id_ikk' => 2,
                'id_terpercaya' => 4,
                'id_landscale' => 2,
                'id_sourceup' => 3,
                'id_kdsd' => 26,
                'target' => '100',
                'satuan' => '%',
                // 'id_capaian' => 11,
                'dokumen' => 'Peta tutupan/penggunaan lahan dengan kelas lahan agroforestri kakao',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            10 =>
            array (
                'id' => 11,
                'indikator' => 'Luas lahan kakao yang berasal dari lahan tidak produktif (semak belukar, lahan terbuka, padang rumput)',
                'stakeholder1' => 'Distan',
                'stakeholder2' => 'Distan',
                'id_intervensi' => 3,
                'id_iku' => 2,
                'id_ikk' => 2,
                'id_terpercaya' => 1,
                'id_landscale' => 4,
                'id_sourceup' => 1,
                'id_kdsd' => 9,
                'target' => '',
                'satuan' => 'ha',
                // 'id_capaian' => 12,
                'dokumen' => 'Data tabular luas dan lokasi lahan kakao yang berasal dari lahan tidak produktif',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            11 =>
            array (
                'id' => 12,
                'indikator' => 'Luas agroforestri kakao',
                'stakeholder1' => 'Distan',
                'stakeholder2' => 'Distan',
                'id_intervensi' => 4,
                'id_iku' => 2,
                'id_ikk' => 2,
                'id_terpercaya' => 1,
                'id_landscale' => 5,
                'id_sourceup' => 1,
                'id_kdsd' => 26,
                'target' => '',
                'satuan' => 'ha',
                // 'id_capaian' => 13,
                'dokumen' => 'Peta tutupan/penggunaan lahan dengan kelas lahan agroforestri kakao',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            12 =>
            array (
                'id' => 13,
                'indikator' => 'Luas pertambahan tutupan lahan agroforestri kakao',
                'stakeholder1' => 'Distan',
                'stakeholder2' => 'Distan',
                'id_intervensi' => 4,
                'id_iku' => 2,
                'id_ikk' => 2,
                'id_terpercaya' => 1,
                'id_landscale' => 5,
                'id_sourceup' => 1,
                'id_kdsd' => 26,
                'target' => '',
                'satuan' => 'ha',
                // 'id_capaian' => 14,
                'dokumen' => 'Data tabular luas dan lokasi agroforestri kakao',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            13 =>
            array (
                'id' => 14,
                'indikator' => 'Luas lahan agroforestri kakao dengan tanaman pangan',
                'stakeholder1' => 'DPUTRPKP2',
                'stakeholder2' => 'DPUTRPKP2',
                'id_iku' => 1,
                'id_ikk' => 5,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 9,
                'target' => '',
                'satuan' => 'ha',
                // 'id_capaian' => 15,
                'id_intervensi' => 4,
                'dokumen' => 'Peta tutupan/penggunaan lahan dengan kelas lahan agroforestri kakao',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            14 =>
            array (
                'id' => 15,
                'indikator' => 'Persentase jumlah petani kakao yang memiliki sertifikat lahan ',
                'stakeholder1' => 'Badan Pertanahan Nasional (BPN)',
                'stakeholder2' => 'Distan',
                'id_intervensi' => 5,
                'id_iku' => 3,
                'id_ikk' => 3,
                'id_terpercaya' => 5,
                'id_landscale' => 6,
                'id_sourceup' => 4,
                'id_kdsd' => 7,
                'target' => '100',
                'satuan' => '%',
                // 'id_capaian' => 16,
                'dokumen' => 'Data tabular status dan luas lahan petani kakao',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            15 =>
            array (
                'id' => 16,
                'indikator' => 'Persentase luas lahan kakao yang memperoleh sertifikat',
                'stakeholder1' => 'Badan Pertanahan Nasional (BPN)',
                'stakeholder2' => 'Distan',
                'id_intervensi' => 5,
                'id_iku' => 3,
                'id_ikk' => 3,
                'id_terpercaya' => 5,
                'id_landscale' => 6,
                'id_sourceup' => 4,
                'id_kdsd' => 7,
                'target' => '100',
                'satuan' => '%',
                // 'id_capaian' => 17,
                'dokumen' => 'Data tabular status dan luas lahan petani kakao',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            16 =>
            array (
                'id' => 17,
                'indikator' => 'Jumlah perhutanan sosial berbasis kakao',
                'stakeholder1' => 'Kesatuan Pengelolaan Hutan (KPH)',
                'stakeholder2' => 'Kesatuan Pengelolaan Hutan (KPH)',
                'id_intervensi' => 6,
                'id_iku' => 1,
                'id_ikk' => 6,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'unit',
                // 'id_capaian' => 19,
                'dokumen' => 'RKPS/RKT kelompok perhutanan sosial yang mengelola kakao',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            17 =>
            array (
                'id' => 18,
                'indikator' => 'Jumlah kemitraan perhutanan sosial yang terjalin ',
                'stakeholder1' => 'Kesatuan Pengelolaan Hutan (KPH)',
                'stakeholder2' => 'Kesatuan Pengelolaan Hutan (KPH)',
                'id_intervensi' => 6,
                'id_iku' => 1,
                'id_ikk' => 6,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'unit',
                // 'id_capaian' => 25,
                'dokumen' => 'Data tabular kemitraan KPS/KUPS dengan pihak lain ',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            18 =>
            array (
                'id' => 19,
                'indikator' => 'Jumlah kelembagaan perhutanan sosial yang aktif',
                'stakeholder1' => 'Kesatuan Pengelolaan Hutan (KPH)',
                'stakeholder2' => 'Kesatuan Pengelolaan Hutan (KPH)',
                'id_intervensi' => 6,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'unit',
                // 'id_capaian' => '',
                'dokumen' => 'Data tabular KPS dan KUPS perhutanan sosial berbasis kakao beserta unit usaha dan status KUPS',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            19 =>
            array (
                'id' => 20,
                'indikator' => 'Jumlah pendampingan perhutanan sosial',
                'stakeholder1' => 'Kesatuan Pengelolaan Hutan (KPH)',
                'stakeholder2' => 'Kesatuan Pengelolaan Hutan (KPH)',
                'id_intervensi' => 6,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '40',
                'satuan' => 'kegiatan',
                // 'id_capaian' => '',
                'dokumen' => 'Data tabular jumlah kegiatan pendampingan kelompok perhutanan sosial disertai dokumentasi',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            20 =>
            array (
                'id' => 21,
                'indikator' => 'Jumlah penyuluh berkompetensi',
                'stakeholder1' => 'Dinas Pertanian Kabupaten',
                'stakeholder2' => 'Dinas Pertanian Kabupaten',
                'id_intervensi' => 7,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 6,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 15,
                'target' => '',
                'satuan' => 'orang',
                // 'id_capaian' => 33,
                'dokumen' => 'Data tabular jumlah penyuluh kakao, jumlah petani kakao, dan rasio penyuluh terhadap petani',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            21 =>
            array (
                'id' => 22,
                'indikator' => 'Rasio penyuluh dan jumlah petani ',
                'stakeholder1' => 'Dinas Pertanian Kabupaten',
                'stakeholder2' => 'Dinas Pertanian Kabupaten',
                'id_intervensi' => 7,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 6,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 15,
                'target' => '0,004',
                'satuan' => '',
                // 'id_capaian' => 34,
                'dokumen' => 'Data tabular jumlah penyuluh, jumlah petani, dan rasio penyuluh terhadap petani',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            22 =>
            array (
                'id' => 23,
                'indikator' => 'Jumlah kegiatan penyuluhan dalam satu tahun',
                'stakeholder1' => 'Dinas Pertanian Kabupaten',
                'stakeholder2' => 'Dinas Pertanian Kabupaten',
                'id_intervensi' => 7,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 6,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 15,
                'target' => '40',
                'satuan' => 'kegiatan',
                // 'id_capaian' => 35,
                'dokumen' => 'Data tabular kegiatan penyuluhan yang dilaksanakan beserta dokumentasi',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            23 =>
            array (
                'id' => 24,
                'indikator' => 'Jumlah pelatihan bagi tenaga penyuluh',
                'stakeholder1' => 'Dinas Pertanian Kabupaten',
                'stakeholder2' => 'Dinas Pertanian Kabupaten',
                'id_intervensi' => 7,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 15,
                'target' => '20',
                'satuan' => 'kegiatan',
                // 'id_capaian' => 43,
                'dokumen' => 'Data tabular kegiatan pelatihan yang dilaksanakan beserta dokumentasi',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            24 =>
            array (
                'id' => 25,
                'indikator' => 'Jumlah petani yang mengikuti kegiatan penyuluhan ',
                'stakeholder1' => 'Dinas Pertanian Kabupaten',
                'stakeholder2' => 'Dinas Pertanian Kabupaten',
                'id_intervensi' => 7,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 6,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 15,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 44,
                'dokumen' => 'Data tabular kegiatan penyuluhan yang dilaksanakan beserta dokumentasi',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            25 =>
            array (
                'id' => 26,
                'indikator' => 'Indeks Nilai Tukar Petani (NTP)',
                'stakeholder1' => 'BPS',
                'stakeholder2' => 'Bappelitbangda',
                'id_intervensi' => 7,
                'id_iku' => 4,
                'id_ikk' => 9,
                'id_terpercaya' => 7,
                'id_landscale' => 7,
                'id_sourceup' => 5,
                'id_kdsd' => 10,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 47,
                'dokumen' => 'Data tabular nilai tukar petani (NTP)',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            26 =>
            array (
                'id' => 27,
                'indikator' => 'Jumlah koperasi dengan unit usaha berbasis kakao',
                'stakeholder1' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan UKM Kabupaten',
                'stakeholder2' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan UKM Kabupaten',
                'id_intervensi' => 8,
                'id_iku' => 1,
                'id_ikk' => 7,
                'id_terpercaya' => 8,
                'id_landscale' => 1,
                'id_sourceup' => 6,
                'id_kdsd' => 4,
                'target' => '9',
                'satuan' => 'unit',
                // 'id_capaian' => 48,
                'dokumen' => 'Data tabular jumlah koperasi dengan unit usaha berbasis kakao',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            27 =>
            array (
                'id' => 28,
                'indikator' => 'Jumlah BUMDes dengan unit usaha berbasis kakao',
                'stakeholder1' => 'Dinas Pemberdayaan Masyarakat dan Desa Kabupaten',
                'stakeholder2' => 'Dinas Pemberdayaan Masyarakat dan Desa Kabupaten',
                'id_intervensi' => 8,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 4,
                'target' => '9',
                'satuan' => 'unit',
                // 'id_capaian' => 49,
                'dokumen' => 'Data tabular unit usaha BUMDES',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            28 =>
            array (
                'id' => 29,
                'indikator' => 'Jumlah petani yang mendapat bantuan permodalan',
                'stakeholder1' => 'DP2KUKM, TA Readsi',
                'stakeholder2' => 'DP2KUKM',
                'id_intervensi' => 8,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 6,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 3,
                'target' => '',
                'satuan' => 'orang',
                // 'id_capaian' => 50,
                'dokumen' => 'Data tabular petani kakao yang memperoleh KUR Pertanian/Kredit Mikro lainnya',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            29 =>
            array (
                'id' => 30,
                'indikator' => 'Jumlah korporasi petani kakao',
                'stakeholder1' => 'Dinas Pertanian Kabupaten',
                'stakeholder2' => 'Dinas Pertanian (Bidang Penyuluhan)',
                'id_intervensi' => 9,
                'id_iku' => 1,
                'id_ikk' => 9,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 6,
                'id_kdsd' => 18,
                'target' => '1',
                'satuan' => 'unit',
                // 'id_capaian' => 57,
                'dokumen' => 'Rencana kelola Korporasi Petani',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            30 =>
            array (
                'id' => 31,
                'indikator' => 'Persentase petani yang tergabung dalam korporasi petani',
                'stakeholder1' => 'Mars, Asosiasi Kakao Doktor, Dinas Pertanian (Bidang Penyuluhan)',
                'stakeholder2' => 'Dinas Pertanian (Bidang Penyuluhan)',
                'id_intervensi' => 9,
                'id_iku' => 1,
                'id_ikk' => 9,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 6,
                'id_kdsd' => 18,
                'target' => '70',
                'satuan' => '%',
                // 'id_capaian' => 58,
                'dokumen' => 'Data tabular anggota korporasi petani',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            31 =>
            array (
                'id' => 32,
                'indikator' => 'Luas lahan yang dikelola korporasi petani',
                'stakeholder1' => 'Dinas Pertanian Kabupaten',
                'stakeholder2' => 'Dinas Pertanian (Bidang Penyuluhan)',
                'id_intervensi' => 9,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 18,
                'target' => '',
                'satuan' => 'ha',
                // 'id_capaian' => 61,
                'dokumen' => 'Rencana kelola Korporasi Petani',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            32 =>
            array (
                'id' => 33,
                'indikator' => 'Pendapatan petani kakao',
                'stakeholder1' => 'Dinas Pertanian Kabupaten',
                'stakeholder2' => 'Dinas Pertanian',
                'id_intervensi' => 9,
                'id_iku' => 4,
                'id_ikk' => 8,
                'id_terpercaya' => 1,
                'id_landscale' => 7,
                'id_sourceup' => 7,
                'id_kdsd' => 20,
                'target' => '',
                'satuan' => 'rupiah',
                // 'id_capaian' => '',
                'dokumen' => 'Data tabular hasil survei/sampling pendapatan petani kakao',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            33 =>
            array (
                'id' => 34,
                'indikator' => 'Jumlah pendampingan peningkatan kapasitas korporasi petani',
                'stakeholder1' => 'Dinas Pertanian Kabupaten, Mars, SFITAL, Readsi, NGO',
                'stakeholder2' => 'Bappelitbangda',
                'id_intervensi' => 9,
                'id_iku' => 1,
                'id_ikk' => 9,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 15,
                'target' => '10',
                'satuan' => 'kegiatan',
                // 'id_capaian' => 63,
                'dokumen' => 'Data tabular kegiatan pendampingan korporasi petani disertai dokumentasi',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            34 =>
            array (
                'id' => 35,
                'indikator' => 'Jumlah peralatan pertanian yang terdistribusi dan sesuai dengan kebutuhan petani',
                'stakeholder1' => 'Dinas Pertanian Kabupaten',
                'stakeholder2' => 'Dinas Pertanian Kabupaten (Bidang PSP)',
                'id_intervensi' => 10,
                'id_iku' => 1,
                'id_ikk' => 9,
                'id_terpercaya' => 6,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 19,
                'target' => '20',
                'satuan' => 'unit',
                // 'id_capaian' => 64,
                'dokumen' => 'Laporan penyaluran bantuan peralatan pertanian untuk petani kakao disertai dokumentasi',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            35 =>
            array (
                'id' => 36,
                'indikator' => 'Persentase kelompok tani yang pernah mendapatkan bantuan peralatan pertanian',
                'stakeholder1' => 'Dinas Pertanian Kabupaten',
                'stakeholder2' => 'Dinas Pertanian Kabupaten (Bidang PSP)',
                'id_intervensi' => 10,
                'id_iku' => 1,
                'id_ikk' => 9,
                'id_terpercaya' => 6,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 19,
                'target' => '100',
                'satuan' => '%',
                // 'id_capaian' => 68,
                'dokumen' => 'Laporan penyaluran bantuan peralatan pertanian untuk petani kakao disertai dokumentasi',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            36 =>
            array (
                'id' => 37,
                'indikator' => 'Indeks Nilai Tukar Petani (NTP)',
                'stakeholder1' => 'Dinas Pertanian Kabupaten',
                'stakeholder2' => 'Bappelitbangda',
                'id_intervensi' => 10,
                'id_iku' => 4,
                'id_ikk' => 8,
                'id_terpercaya' => 7,
                'id_landscale' => 7,
                'id_sourceup' => 5,
                'id_kdsd' => 11,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 69,
                'dokumen' => 'Data nilai tukar petani (NTP)',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            37 =>
            array (
                'id' => 38,
                'indikator' => 'Persentase petani perempuan dan pemuda yang mengikuti penyuluhan usaha tani kakao',
                'stakeholder1' => 'Dinas Pertanian Kabupaten, Mars, SFITAL, Readsi, NGO, Save the Children, Active',
                'stakeholder2' => 'Bappelitbangda',
                'id_intervensi' => 11,
                'id_iku' => 1,
                'id_ikk' => 10,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '30',
                'satuan' => '%',
                // 'id_capaian' => 71,
                'dokumen' => 'Laporan kegiatan penyuluhan usaha tani kakao yang terpilah gender',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            38 =>
            array (
                'id' => 39,
                'indikator' => 'Jumlah petani perempuan kakao dan pemuda yang mengikuti penyuluhan non pertanian',
                'stakeholder1' => 'Dinas Pertanian Kabupaten, Mars, SFITAL, Readsi, NGO, DP3A,  Save the Children, Active',
                'stakeholder2' => 'Bappelitbangda',
                'id_iku' => 1,
                'id_ikk' => 10,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'orang',
                // 'id_capaian' => 72,
                'id_intervensi' => 11,
                'dokumen' => 'Laporan kegiatan penyuluhan usaha tani kakao yang terpilah gender',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            39 =>
            array (
                'id' => 40,
                'indikator' => 'Jumlah unit usaha pengolahan kakao yang dikelola oleh kelompok perempuan',
                'stakeholder1' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan UKM Kabupaten',
                'stakeholder2' => 'DP2KUKM',
                'id_intervensi' => 11,
                'id_iku' => 1,
                'id_ikk' => 10,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '9',
                'satuan' => 'unit',
                // 'id_capaian' => 73,
                'dokumen' => 'Data unit usaha kakao beserta pengelolanya',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            40 =>
            array (
                'id' => 41,
                'indikator' => 'Persentase kelompok yang pernah mendapatkan pelatihan K3',
                'stakeholder1' => 'Mars, Olam, perusahaan, Distan, Disnakertrans, Dinkes',
                'stakeholder2' => 'Sekretariat',
                'id_iku' => 1,
                'id_ikk' => 11,
                'id_terpercaya' => 1,
                'id_landscale' => 8,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '100',
                'satuan' => '%',
                // 'id_capaian' => 76,
                'id_intervensi' => 12,
                'dokumen' => 'Laporan kegiatan pelatihan K3 dan kepemilikan alat keselamatan kerja',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            41 =>
            array (
                'id' => 42,
                'indikator' => 'Persentase petani yang memiliki alat keselamatan kerja',
                'stakeholder1' => 'Mars, Olam, perusahaan, Distan, Disnakertrans, Dinkes',
                'stakeholder2' => 'Sekretariat',
                'id_intervensi' => 12,
                'id_iku' => 1,
                'id_ikk' => 11,
                'id_terpercaya' => 1,
                'id_landscale' => 8,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '100',
                'satuan' => '%',
                // 'id_capaian' => 81,
                'dokumen' => 'Laporan kegiatan pelatihan K3 dan kepemilikan alat keselamatan kerja',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            42 =>
            array (
                'id' => 43,
                'indikator' => 'Persentase keluarga petani yang mendapat edukasi perlindungan anak',
                'stakeholder1' => 'Dinas Transmigrasi dan Tenaga Kerja, Save the Children, DP3AP2KB, Mars, Olam',
                'stakeholder2' => 'DP3AP2KB',
                'id_intervensi' => 13,
                'id_iku' => 1,
                'id_ikk' => 11,
                'id_terpercaya' => 1,
                'id_landscale' => 9,
                'id_sourceup' => 8,
                'id_kdsd' => 1,
                'target' => '100',
                'satuan' => '%',
                // 'id_capaian' => 82,
                'dokumen' => 'Laporan kegiatan penyuluhan edukasi perlindungan anak',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            43 =>
            array (
                'id' => 44,
                'indikator' => 'SOP pencegahan dan pengawasan di tingkat komunitas',
                'stakeholder1' => 'Dinas Transmigrasi dan Tenaga Kerja, Save the Children, DP3AP2KB, Mars, Olam',
                'stakeholder2' => 'DP3AP2KB',
                'id_intervensi' => 13,
                'id_iku' => 1,
                'id_ikk' => 11,
                'id_terpercaya' => 1,
                'id_landscale' => 9,
                'id_sourceup' => 8,
                'id_kdsd' => 1,
                'target' => '1',
                'satuan' => 'unit',
                // 'id_capaian' => 83,
                'dokumen' => 'Dokumen SOP pencegahan dan pengawasan pekerja anak',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            44 =>
            array (
                'id' => 45,
                'indikator' => 'Keberadaan regulasi/produk hukum yang mendukung pengembangan kakao lestari ',
                'stakeholder1' => '',
                'stakeholder2' => 'Sekretariat',
                'id_intervensi' => 14,
                'id_iku' => 5,
                'id_ikk' => 1,
                'id_terpercaya' => 9,
                'id_landscale' => 4,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '1',
                'satuan' => 'unit',
                // 'id_capaian' => 84,
                'dokumen' => 'Dokumen peraturan pengembangan kakao lestari',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            45 =>
            array (
                'id' => 46,
                'indikator' => 'Rata-rata persentase pembiayaan dana desa bagi pengelolaan kakao lestari',
                'stakeholder1' => 'Dinas Pemberdayaan Masyarakat dan Desa Kabupaten',
                'stakeholder2' => 'Dinas Pemberdayaan Masyarakat dan Desa Kabupaten',
                'id_intervensi' => 14,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '10',
                'satuan' => '%',
                // 'id_capaian' => 88,
                'dokumen' => 'Laporan penggunaan dana desa di Kecamatan Baebunta, Baebunta Selatan, Malangke, Malangke Barat, Mappedeceng, Masamba, Rampi, Rongkong, Sabbang, Sabbang Selatan, Seka, Sukamaju, Tanalili',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            46 =>
            array (
                'id' => 47,
                'indikator' => 'Persentase petani kakao yang menerima program asuransi pertanian',
                'stakeholder1' => 'Program Active (500 petani mengikuti program sertifikasi), Olam ',
                'stakeholder2' => 'Sekretariat',
                'id_intervensi' => 15,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 13,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 13,
                'target' => '100',
                'satuan' => '%',
                // 'id_capaian' => 89,
                'dokumen' => 'Laporan peserta asuransi petani',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            47 =>
            array (
                'id' => 48,
                'indikator' => 'Fasilitasi asuransi pertanian',
                'stakeholder1' => 'Program Active (500 petani mengikuti program sertifikasi), Olam',
                'stakeholder2' => 'Sekretariat',
                'id_intervensi' => 15,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '1',
                'satuan' => 'kegiatan',
                // 'id_capaian' => '',
                'dokumen' => 'Laporan kegiatan penyuluhan asuransi petani',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            48 =>
            array (
                'id' => 49,
                'indikator' => 'Jumlah kebun sumber benih dan penangkar bibit kakao bersertifikat',
                'stakeholder1' => 'Dinas Pertanian Kabupaten',
                'stakeholder2' => 'Dinas Pertanian Kabupaten',
                'id_intervensi' => 16,
                'id_iku' => 1,
                'id_ikk' => 4,
                'id_terpercaya' => 5,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '9',
                'satuan' => 'unit',
                // 'id_capaian' => 95,
                'dokumen' => 'Data kebun sumber benih bersertifikat mencakup lokasi, pemilik/pengelola, produksi, jenis benih, jenis kebun, luas, pemasaran, dll.',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            49 =>
            array (
                'id' => 50,
                'indikator' => 'Persentase luas kebun kakao multiklon',
                'stakeholder1' => 'Dinas Pertanian Kabupaten',
                'stakeholder2' => 'Dinas Pertanian Kabupaten',
                'id_intervensi' => 16,
                'id_iku' => 1,
                'id_ikk' => 4,
                'id_terpercaya' => 1,
                'id_landscale' => 12,
                'id_sourceup' => 4,
                'id_kdsd' => 1,
                'target' => '70',
                'satuan' => '%',
                // 'id_capaian' => 96,
                'dokumen' => 'Laporan kepemilikan lahan petani kakao (mencantumkan koordinat kebun, jenis kebun, penerapan konservasi tanah)',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            50 =>
            array (
                'id' => 51,
                'indikator' => 'Persentase petani yang menggunakan benih/bibit kakao unggul (bersertifikat)',
                'stakeholder1' => 'Dinas Pertanian Kabupaten',
                'stakeholder2' => 'Dinas Pertanian Kabupaten',
                'id_intervensi' => 16,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 13,
                'id_landscale' => 12,
                'id_sourceup' => 4,
                'id_kdsd' => 13,
                'target' => '100',
                'satuan' => '%',
                // 'id_capaian' => 98,
                'dokumen' => 'Laporan penggunaan bibit kakao oleh petani',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            51 =>
            array (
                'id' => 52,
                'indikator' => 'Produksi kakao',
                'stakeholder1' => 'Dinas Pertanian Kabupaten, BPS Kabupaten',
                'stakeholder2' => 'Dinas Pertanian Kabupaten',
                'id_intervensi' => 16,
                'id_iku' => 6,
                'id_ikk' => 4,
                'id_terpercaya' => 1,
                'id_landscale' => 13,
                'id_sourceup' => 4,
                'id_kdsd' => 10,
                'target' => '',
                'satuan' => 'ton',
                // 'id_capaian' => 101,
                'dokumen' => 'Data produksi kakao Kabupaten Luwu Utara setiap tahun',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            52 =>
            array (
                'id' => 53,
                'indikator' => 'Produktivitas kakao',
                'stakeholder1' => 'Dinas Pertanian Kabupaten, BPS Kabupaten',
                'stakeholder2' => 'Dinas Pertanian Kabupaten',
                'id_intervensi' => 16,
                'id_iku' => 6,
                'id_ikk' => 4,
                'id_terpercaya' => 7,
                'id_landscale' => 13,
                'id_sourceup' => 4,
                'id_kdsd' => 10,
                'target' => '12000',
                'satuan' => 'ton per ha',
                // 'id_capaian' => 102,
                'dokumen' => 'Data produktivitas kakao',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            53 =>
            array (
                'id' => 54,
                'indikator' => 'Jumlah produsen pupuk organik',
                'stakeholder1' => 'Dinas Pertanian Kabupaten, BPS Kabupaten',
                'stakeholder2' => 'Dinas Pertanian Kabupaten',
                'id_intervensi' => 16,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 13,
                'id_landscale' => 11,
                'id_sourceup' => 4,
                'id_kdsd' => 13,
                'target' => '9',
                'satuan' => 'unit',
                // 'id_capaian' => 103,
                'dokumen' => 'Data produsen pupuk organik yang sudah memiliki nomor pendaftaran',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            54 =>
            array (
                'id' => 55,
                'indikator' => 'Persentase petani kakao yang menggunakan pupuk organik',
                'stakeholder1' => 'Dinas Pertanian Kabupaten',
                'stakeholder2' => 'Dinas Pertanian Kabupaten',
                'id_intervensi' => 16,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 13,
                'id_landscale' => 11,
                'id_sourceup' => 4,
                'id_kdsd' => 13,
                'target' => '100',
                'satuan' => '%',
                // 'id_capaian' => 104,
                'dokumen' => 'Data penggunaan pupuk petani kakao ',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            55 =>
            array (
                'id' => 56,
                'indikator' => 'Persentase petani kakao yang menerapkan teknik konservasi lahan',
                'stakeholder1' => 'Olam, SFITAL, Readsi',
                'stakeholder2' => 'Sekretariat',
                'id_intervensi' => 16,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 17,
                'id_sourceup' => 4,
                'id_kdsd' => 1,
                'target' => '100',
                'satuan' => '%',
                // 'id_capaian' => 105,
                'dokumen' => 'Laporan kepemilikan lahan petani kakao (mencantumkan koordinat kebun, jenis kebun, penerapan konservasi tanah)',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            56 =>
            array (
                'id' => 57,
                'indikator' => 'Persentase petani kakao yang menerapkan agroforestri kakao',
                'stakeholder1' => 'Dinas Pertanian Kabupaten, SFITAL, Olam, Mars, Active, Laskar Kakao, Masagena, universitas',
                'stakeholder2' => 'Sekretariat',
                'id_intervensi' => 16,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 12,
                'id_sourceup' => 4,
                'id_kdsd' => 13,
                'target' => '60',
                'satuan' => '%',
                // 'id_capaian' => 106,
                'dokumen' => 'Laporan kepemilikan lahan petani kakao (mencantumkan koordinat kebun, jenis kebun, penerapan konservasi tanah)',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            57 =>
            array (
                'id' => 58,
                'indikator' => 'Persentase petani yang mendapatkan pelatihan agroforestri kakao',
                'stakeholder1' => 'Dinas Pertanian Kabupaten, SFITAL, Olam, Mars, Active, Laskar Kakao, Masagena, universitas',
                'stakeholder2' => 'Sekretariat',
                'id_intervensi' => 16,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 13,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 13,
                'target' => '100',
                'satuan' => '%',
                // 'id_capaian' => 107,
                'dokumen' => 'Laporan penyuluhan petani kakao',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            58 =>
            array (
                'id' => 59,
                'indikator' => 'Jumlah kios pupuk bersubsidi untuk tanaman kakao',
                'stakeholder1' => 'DP2KUKM, Dinas Pertanian (PSP)',
                'stakeholder2' => 'DP2KUKM',
                'id_intervensi' => 17,
                'id_iku' => 1,
                'id_ikk' => 4,
                'id_terpercaya' => 13,
                'id_landscale' => 11,
                'id_sourceup' => 4,
                'id_kdsd' => 13,
                'target' => '9',
                'satuan' => 'unit',
                // 'id_capaian' => 111,
                'dokumen' => 'Data jumlah kios pupuk bersubsidi',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            59 =>
            array (
                'id' => 60,
                'indikator' => 'Jumlah pelatihan dan peningkatan kapasitas petani dalam peningkatan mutu dan pasca panen',
                'stakeholder1' => 'Dinas Pertanian Kabupaten; Mars, Mars, mitra pembangunan, DP2KUKM, universitas, DPKP ',
                'stakeholder2' => 'Sekretariat',
                'id_intervensi' => 18,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 13,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 13,
                'target' => '1',
                'satuan' => 'kegiatan',
                // 'id_capaian' => 114,
                'dokumen' => 'Laporan penyuluhan petani kakao',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            60 =>
            array (
                'id' => 61,
                'indikator' => 'Jumlah petani yang dilatih untuk peningkatan mutu dan pasca panen',
                'stakeholder1' => 'Dinas Pertanian Kabupaten; Mars, Mars, mitra pembangunan, DP2KUKM, universitas, DPKP',
                'stakeholder2' => 'Sekretariat',
                'id_intervensi' => 18,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 13,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 22,
                'target' => '100',
                'satuan' => '%',
                // 'id_capaian' => 115,
                'dokumen' => 'Laporan penyuluhan petani kakao',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),

            61 =>
            array (
                'id' => 62,
                'indikator' => 'Persentase rata-rata nilai tambah bisnis industri hilir skala kecil',
                'stakeholder1' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan Usaha Kecil Menengah',
                'stakeholder2' => 'DP2KUKM (Bidang Perindustrian)',
                'id_intervensi' => 18,
                'id_iku' => 6,
                'id_ikk' => 16,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 23,
                'target' => '25',
                'satuan' => '%',
                // 'id_capaian' => 119,
                'dokumen' => 'Data unit usaha kakao beserta pengelolanya',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            62 =>
            array (
                'id' => 63,
                'indikator' => 'Persentase volume kakao fermentasi yang diproduksi oleh petani/kelompok tani/smallholder',
                'stakeholder1' => 'Dinas Pertanian Kabupaten; Mars; Koperasi Simultan, Koperasi Masagena ',
                'stakeholder2' => 'Dinas Pertanian',
                'id_intervensi' => 18,
                'id_iku' => 6,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '60',
                'satuan' => '%',
                // 'id_capaian' => 120,
                'dokumen' => 'Data produksi biji kakao beserta kualitas mutunya berdasarkan SNI',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            63 =>
            array (
                'id' => 64,
                'indikator' => 'Jumlah jenis produk kakao yang dihasilkan kelompok petani/masyarakat',
                'stakeholder1' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan Usaha Kecil Menengah',
                'stakeholder2' => 'DP2KUKM',
                'id_intervensi' => 18,
                'id_iku' => 1,
                'id_ikk' => 16,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'unit',
                // 'id_capaian' => 122,
                'dokumen' => 'Data unit usaha kakao beserta pengelolanya',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            64 =>
            array (
                'id' => 65,
                'indikator' => 'Jumlah unit usaha produk turunan kakao yang dikelola masyarakat',
                'stakeholder1' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan Usaha Kecil Menengah',
                'stakeholder2' => 'DP2KUKM',
                'id_intervensi' => 19,
                'id_iku' => 6,
                'id_ikk' => 16,
                'id_terpercaya' => 10,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 22,
                'target' => '',
                'satuan' => 'unit',
                // 'id_capaian' => 121,
                'dokumen' => 'Data unit usaha kakao beserta pengelolanya',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            65 =>
            array (
                'id' => 66,
                'indikator' => 'Persentase produksi biji dengan kelas mutu I dan II (SNI 2323:2008)',
                'stakeholder1' => 'Mars, Olam, perusahaan',
                'stakeholder2' => 'Sekretariat',
                'id_intervensi' => 20,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '70',
                'satuan' => '%',
                // 'id_capaian' => 126,
                'dokumen' => 'Data produksi biji kakao beserta kualitas mutunya berdasarkan SNI',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            66 =>
            array (
                'id' => 67,
                'indikator' => 'Jumlah koperasi petani kakao dan BUMDes dengan unit usaha kakao',
                'stakeholder1' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan Usaha Kecil Menengah, DPMD',
                'stakeholder2' => 'Dinas Perdagangan, Perindustrian, Koperasi, dan Usaha Kecil Menengah, DPMD',
                'id_intervensi' => 20,
                'id_iku' => 6,
                'id_ikk' => 16,
                'id_terpercaya' => 8,
                'id_landscale' => 1,
                'id_sourceup' => 6,
                'id_kdsd' => 21,
                'target' => '9',
                'satuan' => 'unit',
                // 'id_capaian' => 130,
                'dokumen' => 'Data koperasi di tingkat desa, kecamatan, kabupaten dan unit usaha BUMDes',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            67 =>
            array (
                'id' => 68,
                'indikator' => 'Persentase petani yang melakukan pengarsipan dokumen dan pencatatan usaha tani',
                'stakeholder1' => 'Mars, Olam, perusahaan',
                'stakeholder2' => 'Sekretariat',
                'id_intervensi' => 21,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '100',
                'satuan' => '%',
                // 'id_capaian' => 132,
                'dokumen' => 'Laporan penyuluhan petani kakao',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            68 =>
            array (
                'id' => 69,
                'indikator' => 'Persentase petani kakao yang memiliki informasi koordinat',
                'stakeholder1' => 'Olam, Mars, perusahaan',
                'stakeholder2' => 'Dinas Pertanian',
                'id_intervensi' => 22,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 5,
                'id_landscale' => 1,
                'id_sourceup' => 4,
                'id_kdsd' => 14,
                'target' => '100',
                'satuan' => '%',
                // 'id_capaian' => 135,
                'dokumen' => 'Laporan kepemilikan lahan petani kakao (mencantumkan koordinat kebun, jenis kebun, penerapan konservasi tanah)',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            69 =>
            array (
                'id' => 70,
                'indikator' => 'Persentase petani mengikuti sertifikasi komoditas kakao berkelanjutan',
                'stakeholder1' => 'Mars, Olam, Cargill, Masagena',
                'stakeholder2' => 'Sekretariat',
                'id_intervensi' => 22,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 5,
                'id_landscale' => 1,
                'id_sourceup' => 4,
                'id_kdsd' => 14,
                'target' => '100',
                'satuan' => '%',
                // 'id_capaian' => 137,
                'dokumen' => 'Laporan sertifikasi komoditas kakao',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            70 =>
            array (
                'id' => 71,
                'indikator' => 'Indeks Risiko Bencana',
                'stakeholder1' => 'BPBD',
                'stakeholder2' => 'BPBD',
                'id_intervensi' => 23,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 5,
                'id_landscale' => 1,
                'id_sourceup' => 4,
                'id_kdsd' => 14,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 137,
                'dokumen' => 'Laporan/dokumen Indeks Risiko Bencana',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            71 =>
            array (
                'id' => 72,
                'indikator' => 'IKLH (Tupla, udara dan air)',
                'stakeholder1' => 'DLH',
                'stakeholder2' => 'DLH',
                'id_intervensi' => 23,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 5,
                'id_landscale' => 1,
                'id_sourceup' => 4,
                'id_kdsd' => 14,
                'target' => '',
                'satuan' => '',
                // 'id_capaian' => 137,
                'dokumen' => 'Laporan pengukuran IKLH',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            72 =>
            array (
                'id' => 73,
                'indikator' => 'Debit air sungai',
                'stakeholder1' => 'DPUTRPKP2',
                'stakeholder2' => 'DPUTRPKP2',
                'id_intervensi' => 23,
                'id_iku' => 2,
                'id_ikk' => 2,
                'id_terpercaya' => 3,
                'id_landscale' => 3,
                'id_sourceup' => 1,
                'id_kdsd' => 26,
                'target' => '',
                'satuan' => 'm3 per detik',
                // 'id_capaian' => 142,
                'dokumen' => 'Laporan pengukuran debit air',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            73 =>
            array (
                'id' => 74,
                'indikator' => 'Volume pembiayaan pemerintah untuk mendukung biaya TAKE dan biaya transfer KIJLH',
                'stakeholder1' => 'Bappelitbangda',
                'stakeholder2' => 'Bappelitbangda',
                'id_intervensi' => 23,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => '%',
                // 'id_capaian' => 145,
                'dokumen' => 'Laporan pembiayaan TAKE dan KIJLH',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            74 =>
            array (
                'id' => 75,
                'indikator' => 'Jumlah program terkait pengelolaan jasa lingkungan',
                'stakeholder1' => 'Bappelitbangda',
                'stakeholder2' => 'Bappelitbangda',
                'id_intervensi' => 23,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '1',
                'satuan' => 'kegiatan',
                // 'id_capaian' => '',
                'dokumen' => 'Laporan pelaksanaan program pengelolaan jasa lingkunga',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            75 =>
            array (
                'id' => 76,
                'indikator' => 'Jumlah petani peserta PJLH',
                'stakeholder1' => 'DLH',
                'stakeholder2' => 'DLH',
                'id_intervensi' => 24,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 6,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'orang',
                // 'id_capaian' => 149,
                'dokumen' => 'Laporan pelaksanaan PJLH',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            76 =>
            array (
                'id' => 77,
                'indikator' => 'Jumlah produk kakao Luwu Utara yang memperoleh label ramah lingkungan hidup',
                'stakeholder1' => 'DP2KUKM',
                'stakeholder2' => 'DP2KUKM',
                'id_intervensi' => 25,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 5,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 17,
                'target' => '100',
                'satuan' => '%',
                // 'id_capaian' => 153,
                'dokumen' => 'Laporan unit usaha produk turunan kakao',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            77 =>
            array (
                'id' => 78,
                'indikator' => 'Volume dana penanggulangan, pencemaran dan/atau kerusakan dan pemulihan lingkungan hidup',
                'stakeholder1' => 'DLH',
                'stakeholder2' => 'DLH',
                'id_intervensi' => 26,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 5,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '',
                'satuan' => 'rupiah',
                // 'id_capaian' => 154,
                'dokumen' => 'Laporan pelaksanaan kegiatan penanggulangan, pencemaran dan/atau kerusakan dan pemulihan lingkungan hidup',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            78 =>
            array (
                'id' => 79,
                'indikator' => 'Jumlah perusahaan, kelompok masyarakat, maupun perorangan yang mendapat penghargaan kinerja di bidang perlindungan lingkungan',
                'stakeholder1' => 'DLH',
                'stakeholder2' => 'DLH',
                'id_intervensi' => 27,
                'id_iku' => 1,
                'id_ikk' => 1,
                'id_terpercaya' => 1,
                'id_landscale' => 1,
                'id_sourceup' => 1,
                'id_kdsd' => 1,
                'target' => '1',
                'satuan' => 'kelompok',
                // 'id_capaian' => 156,
                'dokumen' => 'Laporan pemberian penghargaan lingkungan hidup',
                // 'status' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            )
        ));
    }
}
